### ISSUE TITLE
Luaposix fails to load on NetBSD

### ISSUE THREAD

**Issue by sparked435** [luaposix/luaposix#199]
Luaposix 33.2.1 compiles without warnings or errors on NetBSD 6.1, but fails attempting to require() the module:

lua5.2: error loading module 'posix.bit32' from file '/usr/local/lib/lua/5.2/posix.so':
        /usr/local/lib/lua/5.2/posix.so: Undefined PLT symbol "slk_refresh" (symnum = 7)

It appears NetBSD's curses implementation is it's own unique animal. Differences with ncurses are documented well here: http://invisible-island.net/ncurses/ncurses-netbsd.html

As a workaround, I was able to build luaposix with ncurses installed via pkgsrc, but this was not an obvious solution when viewing the current documentation or the recieved error messages.

Possible fixes, I'm uncertain which is best for the long term goals of Luaposix:
 - The ability to optionally disable curses support, for those who only need POSIX functions and not curses
 - Clearly state in the README that ncurses support is required (at least for NetBSD), and possibly update configure to check in the pkgsrc directories /usr/pkg/lib, when looking for dependancies
 - Detect presence of vid_attr, vid_puts, slk_*, and scr_* functions and disable them in luaposix if missing on the host system.

**Comment by gvvaughan** [comment]
The only no-no with luaposix is adding suppor for APIS not lusted by the opengroup spec...

So the last of your suggestions is most in keeping with the approach used by the rest of luaposix, and would be very easy to write a patch for given an exhaustive list of the functions missing from NetBSD (which isn't obvious from the link you quote )-:

Care to give it a shot?

**Comment by sparked435** [comment]
Sure, I'll give it a try.
I was able to brute force the following list by commenting out code:

ripoffline
syncok
immedok
slk_attroff
slk_attron
slk_attrset
slk_clear
slk_init
slk_label
slk_noutrefresh
slk_refresh
slk_restore
slk_set
slk_touch

It looks like I can use #ifndef __NetBSD__ to eliminate these functions, but then again some NetBSD users might want to get this functionality back by explicity linking against ncurses. Looks like we'll need another flag in config.h.

Autonconf is a black box who's insides are completely foreign to me. I've got some reading to do before I can go any further.

**Comment by gvvaughan** [comment]
That's a great start, thank you.

I would say it might be possible to figure it out from the preprocessor defines in NetBSD curses vs ncurses: I found a link that says the NetBSD curses wide char implementation is different, so maybe it's as simple as adding:

```c
#ifndef NCURSES_WIDECHAR
#  define NETBSD_CURSES
#endif
```

Which will continue to bind the full interface on NetBSD with ncurses.  Alternatively, does NetBDS define any of: `NCURSES_VERSION`, `NCURSES_VERSION_MAJOR`, `NCURSES_VERSION_MINOR`, `NCURSES_VERSION_PATCH`, `NCURSES_MOUSE_VERSION`.  Or, what about whether there's a cursslk.h header in the same directory as curses.h/ncurses.h?

**Comment by sparked435** [comment]
There appears to be no cursslk.h header file at all on NetBSD.

Here's the preprocessor code that controls wide characters:

 ` #if !defined(HAVE_WCHAR) && !defined(DISABLE_WCHAR)`
`  #define HAVE_WCHAR 1`
`  #endif`

No versioning defines are set either.

I'm thinking if `_NetBSD_` is defined and `NCURSES_VERSION` is not, disable the missing functions. Any thoughts or concerns?

**Comment by gvvaughan** [comment]
I'm always happier to find a solution with CPP defines than to add more autotools glue.  The combination of `_NetBSD_` and `NCURSES_VERSION` to decide on whether to bind the functions you discovered to be missing is definitely the right approach.  Probably the wide-char defines were a red-herring, and can be ignored with this more obvious solution.

A nice enhancement might be to also add a stub function that returns `nil, "this function is not available in the system libraries, unless you relink luaposix against nurses"` or similar, and then bind the missing functions to the stub?

**Comment by sparked435** [comment]
Patch completed; pull request sent.

**Comment by gvvaughan** [comment]
Merged at e43759c.  Thank you!

**Comment by rsmarples** [comment]
As of today, these functions exist in NetBSD.
http://roy.marples.name/blog/blog/soft-label-keys
