### ISSUE TITLE
'sockaddr' documentation incomplete

### ISSUE THREAD

**Issue by monoped** [luaposix/luaposix#200]
The documentation doesn't mention the field 'path', used for local connections. Probably other fields are missing as well. There should at least a note here indicating that the set of fields depends on the address familiy.

**Comment by gvvaughan** [comment]
Thanks for the report.  Agreed.

I improved the LDocs somewhat tersely, but ultimately the idea of the luaposix documentation is to defer to the SUSv3 specification for details.  One day, I'd like to have luaposix wrap the C POSIX APIs so thinly, that the code itself will just be a LuaFFI specification, and no documentation for how to transform the C APIs into Lua will be required at all... that day is still somewhat distant, alas!
