### ISSUE TITLE
Use bit32 rock for 5.1 rather than reproduce it in luaposix

### ISSUE THREAD

**Issue by rrthomas** [luaposix/luaposix#204]
There's a backport of the bit32 library to Lua 5.1 available as a rock, so use that instead of reimplementing it.

**Comment by gvvaughan** [comment]
Hi Reuben,

Until luarocks can recognize dependencies per Lua version, this simply undoes the work put into not having a useless luabitop module installed on Lua 5.2 and 5.3.  With barely 20 SLOC saved in luaposix exchanged for a usually not-required additional module installed, there seems little advantage in switching... do you have a compelling argument to the contrary?

**Comment by rrthomas** [comment]
`bit32` is already marked as built in by LuaRocks on Lua >= 5.2.

**Comment by gvvaughan** [comment]
Excellent!  In that case I agree with you.

Feel free to jump in a beat me to the commit :-)

**Comment by gvvaughan** [comment]
...except that I just remembered the reason I added it was not to provide a real bit32 library to luaposix clients, but to support the low-level APIs bit selection and masking without requiring embedded users to shoehorn another dependency they do not need into their build.

So, best not to rely on luarocks bit32 module in this case IMHO.  I'll commit a note to this effect to the top of ext/luaposix/bit32.c so we don't forget again and undo previous good work! :-)

**Comment by rrthomas** [comment]
Did an embedded user or users ask for this or give figures? It seems to me this is catering to what seems to me a small audience, namely one that a) uses an embedded system, b) with POSIX, but c) without bit32. Both b) and c) seem rare to me given a), and bit32) is at most a couple of kb (a stripped object for me is 3.2kb on amd64; on an embedded system it would presumably be smaller; meanwhile, removing bit32.c from luaposix doesn't change the size of the binary; its stripped module is larger than bit32's, but includes helper functions also used elsewhere, so it's clearly at most 1kb or so). As of Lua 5.3 the question is moot anyway: bitwise operations are built in. Therefore, this seems catering to a too-small and in any case now obsolescent audience. Clearly we'll use bit32 for now as we can't use Lua 5.3's bitwise operations in a backwards-compatible way, but equally it seems bootless to worry much about this particular case.

So unless there's evidence of pain from embedded users, I vote again for replacing this stub with a dependency!

**Comment by gvvaughan** [comment]
Hi Reuben,

Yes, it was a specific request (from Zevv?) though I couldn't put my finger on the specific issue after a quick look yesterday. It's also as much to do with (the lack of) LuaRocks as specifically embedded; I get a trickle of ongoing complaints from users who don't or can't use LuaRocks who just want to copy a selection of C files into their custom Lua build.

If you want to apply the changes, I'm not personally affected and won't make any noise... Though breaking the giant C file apart into individually removable sections was arguably for a similar tiny audience, and could be undone by the same argument - which would make me sad!

Cheers,
Gary

**Comment by rrthomas** [comment]
I have agreed previously with keeping luaposix easy to build without a build system (e.g. keeping it a single C file), and of course that's still fine (and the recent split into multiple files doesn't change that, as they're still all `#include`ed into one).

In general, though, support for embedded systems (or anything else currently not well supported) is something that should be solved in the tools, not in luaposix; perhaps next time you get such a request, you could direct them to file a bug/feature request against LuaRocks?
