### ISSUE TITLE
Install ignores --libdir and installs into /usr/lib/..

### ISSUE THREAD

**Issue by opoplawski** [luaposix/luaposix#210]
On Fedora, 64-bit libraries need to go into /usr/lib64/....  We specify --libdir=/usr/lib64/lua/5.2 but this is ignored and files are installed into $(luaexecdir)

luaposix is defining luaexecdir as:

luaposix-release-v33.2.1/m4/ax_lua.m4:        ax_cv_lua_luaexecdir="$LUA_EXEC_PREFIX/lib/lua/$LUA_VERSION"

**Comment by gvvaughan** [comment]
This report needs to go upstream to the autoconf macro archive, which owns ax_lua.m4.

In the mean time, can you also set LUA_EXEC_PREFIX at configure and/or install time as a work around?

**Comment by opoplawski** [comment]
No, the problem is the hardcoded "lib" that follows it.  I can however sed it.

https://github.com/peti/autoconf-archive/pull/27 is the upstream fix.

**Comment by rrthomas** [comment]
The upstream fix has been pushed, so slingshot can now update to fix this issue.

**Comment by gvvaughan** [comment]
Thanks!  Merged and synced.
