### ISSUE TITLE
No `init.lua` installed in 33.3.0

### ISSUE THREAD

**Issue by rrthomas** [luaposix/luaposix#214]
Glad that you worked around the luarocks problem, sad that you broke the world for me, as I like to `require "posix"`.

**Comment by rrthomas** [comment]
I used `luarocks install luaposix`, nothing fancy!

**Comment by rrthomas** [comment]
The relevant line from the build says:

     /usr/bin/install -c -m 644 lib/posix/_argcheck.lua lib/posix/compat.lua lib/posix/deprecated.lua lib/posix/sys.lua lib/posix/util.lua '/home/rrt/.local/lib/luarocks/rocks-5.2/luaposix/33.3.0-1/lua/posix'

i.e. definitely no `init.lua`.

**Comment by rrthomas** [comment]
OK, it's been installed in the wrong place. I'll push a fix and leave you to make a new release :)

**Comment by rrthomas** [comment]
Fixed by 2def3b9.

**Comment by rrthomas** [comment]
By the way, this raises a couple of other issues:

1. Add a test that `require "posix"` works.
2. Rename the shared library, as when I ran into this issue I got an error about `luaopen_posix` not existing, which is sort of right, but rather confusing.

**Comment by gvvaughan** [comment]
Thanks for cleaning up my mess! :-)

1. Agreed, and yes... I think that means we need to ensure `make installcheck` works, and have slingshot do that as part of the travis checks.  I'll do that before releasing 33.3.1.  I should probably retract 33.3.0 as utterly b0rken :-(
2. Disagreed.  posix.so is a collection of modules using the fourth *all-in-one* searcher from `package.loaders` as described in the reference docs, so any other name would equally be a misnomer, and arguably even more confusing.  Besides, once `init.lua` is installed correctly, you shouldn't get this error message in any case.

**Comment by rrthomas** [comment]
I see what you mean about the shared library, but perhaps have a stub `luaopen_posix` function that raises an error, so that it's possible to tell that the library has been mis-installed?
