### ISSUE TITLE
Broken links to pubs.opengroup.org from luaposix Reference

### ISSUE THREAD

**Issue by starius** [luaposix/luaposix#220]
See https://luaposix.github.io/luaposix/classes/posix.curses.window.html
External links (e.g. [curs_outopts(3x)](http://pubs.opengroup.org/onlinepubs/009695399/functions/curs_outopts.html)) are broken.

**Comment by gvvaughan** [comment]
Thanks for the reminder... I'll make sure to fix this before the next release.
