### ISSUE TITLE
Missing parameters y and x in description of posix.curses.window:mvaddch

### ISSUE THREAD

**Issue by starius** [luaposix/luaposix#221]
Function posix.curses.window:mvaddch [gets](https://github.com/luaposix/luaposix/blob/e43759c923d992be1c5446017fb36612a468a4e8/ext/posix/curses/window.c#L784) the following arguments:
 * window
 * y
 * x
 * ch

However y and x are [not included](https://github.com/luaposix/luaposix/blob/e43759c923d992be1c5446017fb36612a468a4e8/ext/posix/curses/window.c#L779) in the description of the function.

**Comment by gvvaughan** [comment]
Thanks for pointing that out... I obviously started to go LDoc blind at some point when I was converting the hundreds of perl script generated docs to LDoc format.  Fixed in master!
