### ISSUE TITLE
bit32 using lua 5.3, still required?

### ISSUE THREAD

**Issue by zerothi** [luaposix/luaposix#224]
This is probably related to #204 ?

I have installed lua 5.3 and subsequently posix 33.3.1 into the same directory using posix configure as this (I install everything by source, and try to do without luarocks):
```
./configure \
	LUA=/opt/lua/5.3.0/bin/lua \
	LUA_INCLUDE='-I/opt/lua/5.3.0/include' \
	--prefix=/opt/lua/5.3.0/ \
	--libdir=/opt/lua/5.3.0/lib/lua/5.3 \
	--datarootdir=/opt/lua/5.3.0/share/lua/5.3/
```

When I then do this in the lua shell:
```
> local posix = require "posix"
```
I get this error message:
`/opt/generic/lua/5.3.0/share/lua/5.3/posix/init.lua:17: module 'bit32' not found`
and then a stack-trace of path searches for `bit32.lua`.

I guess it has to do with the bit32 thing being deprecated in lua 5.3? I am a bit at loss as I just use lua for some of our users.

It isn't clear whether I need to install bit32 on top of lua 5.3.

Any suggestions?

**Comment by zerothi** [comment]
I have just tried installing luarocks and installing bit32, however, I find this:

```
luarocks install bit32                                                                                                                                                                                                    new

Error: Rock bit32 5.3-1 was found but it is provided by VM or 'rocks_provided' in the config file.
```
So it won't even install bit32 as a rock.

**Comment by gvvaughan** [comment]
See also #206

**Comment by zerothi** [comment]
Thanks I did not see that one.

I fixed the issue.

One simply needs these additional flags for building lua-5.3:  
`-DLUA_COMPAT_BITLIB -DLUA_COMPAT_APIINTCASTS`

`-DLUA_COMPAT_BITLIB` requires `-DLUA_COMPAT_APIINTCASTS` to function properly.

I could not find an issue site for lua as I think defining LUA_COMPAT_BITLIB should automatically define LUA_COMPAT_APIINTCASTS.

Yet, I consider the problem fixed on my parts.
Thanks!

**Comment by rrthomas** [comment]
Just to be clear: this problem arises when Lua 5.3 is built with non-default build options. There's nothing LuaRocks can do about that. I have reported to the Lua authors a similar problem with `-DLUA_COMPAT_APIINTCASTS` to that pointed out by @zerothi; no reply as yet.

**Comment by telemachus** [comment]
I'm having this same problem now with a version of Lua 5.3 built by Homebrew on OSX. If I understand this thread correctly, I need to bug them about their build options for Lua?

TIA and apologies for waking an (otherwise) dead issue.

**Comment by zerothi** [comment]
Yes, it seems so... :(

**Comment by gvvaughan** [comment]
Yep, homebrew is using `-DLUA_COMPAT_ALL` in `lua53.rb`, a flag which did not carry forward from PUC-Rio Lua 5.2... this patch works for me:

```diff
diff --git a/lua53.rb b/lua53.rb
index 9a5846f..93a7e1b 100644
--- a/lua53.rb
+++ b/lua53.rb
@@ -36,7 +36,7 @@ class Lua53 < Formula
     # Use our CC/CFLAGS to compile.
     inreplace "src/Makefile" do |s|
       s.remove_make_var! "CC"
-      s.change_make_var! "CFLAGS", "#{ENV.cflags} -DLUA_COMPAT_ALL $(SYSCFLAGS) $(MYCFLAGS)"
+      s.change_make_var! "CFLAGS", "#{ENV.cflags} -DLUA_COMPAT_5_2 $(SYSCFLAGS) $(MYCFLAGS)"
       s.change_make_var! "MYLDFLAGS", ENV.ldflags
     end
```

followed by `brew install --build-from-source lua53`, and then everything works as before:

```bash
$ luarocks-5.3 install luaposix
[[...]]
Updating manifest for /usr/local/lib/luarocks/rocks-5.3                      
luaposix 33.4.0-1 is now built and installed in /usr/local (license: MIT/X11)
$ lua5.3 -e 'print (require "posix".version)'
posix for Lua 5.3 / luaposix 33.4.0                   
```

**Comment by telemachus** [comment]
@gvvaughan Thanks for taking the time to track that down and make the pull request.

**Comment by mpeterv** [comment]
Luarocks 2.4.0+ can handle this by the way, see https://github.com/keplerproject/luarocks/issues/526

**Comment by dipojono** [comment]
I added those two -DLUA's to build lua-5.3 but get the error message:
The follow lua module(s) are missing: posix
Why?
