### ISSUE TITLE
Missing alarm(3) in posix.unistd?

### ISSUE THREAD

**Issue by bblack-cuda** [luaposix/luaposix#225]
Hi there!

Before I go off implementing something silly, is there any particular reason alarm(2) isn't exposed in ext/posix/unistd.c?

It seems like a trivial patch to do (and I'd be happy to write one up), just making sure I'm not about to do something (obviously) stupid...

**Comment by gvvaughan** [comment]
By all means.  Assuming you mean this:

    http://pubs.opengroup.org/onlinepubs/009695399/functions/alarm.html

...then a patch is welcome, and the only reason for omission thus far is that no client currently uses it, or has sent back a suitable implementation!

**Comment by bblack-cuda** [comment]
Submitted pr 226.  Closing this issue...
