### ISSUE TITLE
sys.socket.bind/connect don't support AF_UNIX abstract namespace

### ISSUE THREAD

**Issue by essele** [luaposix/luaposix#232]
When using AF_UNIX, if the path starts with a zero byte then it's the abstract namespace that doesn't require a representation in the filesystem.

Unfortunately luaposix uses strlcpy() to copy the path into the sockaddr_un structure, this will stop at the first zero as it assumes it's the end of the string, therefore the socket is created with an effectively empty name.

The fix is a bit more complex as checkstringfield() used lua_tostring() rather than lua_tolstring() so the real length is lost. My suggestion would be to create a checklstringfield() function that keeps the length, and then use memcpy() rather than strlcpy(), but I haven't looked in detail where this would be needed.

Regards,

Lee.

**Comment by gvvaughan** [comment]
Hi Lee,

Thanks for the report. Sorry for the slow response, it's been a busy week! Would you like to write a patch for this?

Cheers,
Gary

**Comment by essele** [comment]
Hi Gary,

> On 3 Oct 2015, at 23:23, Gary V. Vaughan <notifications@github.com> wrote:
> 
> Hi Lee,
> 
> Thanks for the report. Sorry for the slow response, it's been a busy week! Would you like to write a patch for this?
> 
> Cheers,
> Gary

I think this is right, it’s pretty simple and should be non-impactful on everything else.

The memcpy() length determination to stop the overrun is a bit horrible, but I can’t think of a better way of doing it.

Cheers,

Lee.


diff --git a/ext/include/_helpers.c b/ext/include/_helpers.c
index 48a33bc..8ac0b66 100644
--- a/ext/include/_helpers.c
+++ b/ext/include/_helpers.c
@@ -309,11 +309,11 @@ checknumberfield(lua_State *L, int index, const char *k)
 }
 
 static const char *
-checkstringfield(lua_State *L, int index, const char *k)
+checkstringfield(lua_State *L, int index, const char *k, size_t *len)
 {
 	const char *r;
 	checkfieldtype(L, index, k, LUA_TSTRING, NULL);
-	r = lua_tostring(L, -1);
+	r = lua_tolstring(L, -1, len);
 	lua_pop(L, 1);
 	return r;
 }
@@ -339,7 +339,7 @@ optstringfield(lua_State *L, int index, const char *k, const char *def)
 	lua_pop(L, 1);
 	if (got_type == LUA_TNONE || got_type == LUA_TNIL)
 		return def;
-	return checkstringfield(L, index, k);
+	return checkstringfield(L, index, k, NULL);
 }
 
 static int
diff --git a/ext/posix/sys/socket.c b/ext/posix/sys/socket.c
index 1332091..69b4ead 100644
--- a/ext/posix/sys/socket.c
+++ b/ext/posix/sys/socket.c
@@ -190,7 +190,7 @@ sockaddr_from_lua(lua_State *L, int index, struct sockaddr_storage *sa, socklen_
 		{
 			struct sockaddr_in *sa4 = (struct sockaddr_in *)sa;
 			int port		= checkintfield(L, index, "port");
-			const char *addr	= checkstringfield(L, index, "addr");
+			const char *addr	= checkstringfield(L, index, "addr", NULL);
 
 			checkfieldnames (L, index, Safinet_fields);
 
@@ -207,7 +207,7 @@ sockaddr_from_lua(lua_State *L, int index, struct sockaddr_storage *sa, socklen_
 		{
 			struct sockaddr_in6 *sa6= (struct sockaddr_in6 *)sa;
 			int port		= checkintfield(L, index, "port");
-			const char *addr	= checkstringfield(L, index, "addr");
+			const char *addr	= checkstringfield(L, index, "addr", NULL);
 
 			checkfieldnames (L, index, Safinet_fields);
 
@@ -223,12 +223,13 @@ sockaddr_from_lua(lua_State *L, int index, struct sockaddr_storage *sa, socklen_
 		case AF_UNIX:
 		{
 			struct sockaddr_un *sau	= (struct sockaddr_un *)sa;
-			const char *path	= checkstringfield(L, index, "path");
+			size_t len;
+			const char *path	= checkstringfield(L, index, "path", &len);
 
 			checkfieldnames (L, index, Safunix_fields);
 
 			sau->sun_family	= family;
-			strlcpy(sau->sun_path, path, sizeof(sau->sun_path));
+			memcpy(sau->sun_path, path, ++len < sizeof(sau->sun_path) ? len : sizeof(sau->sun_path));
 			sau->sun_path[sizeof(sau->sun_path) - 1]= '\0';
 			*addrlen	= sizeof(*sau);
 			r		= 0;

**Comment by gvvaughan** [comment]
Hi Lee,

Thanks very much for that!  Code is clearer than a description any day :)

There is no mention of the abstract namespace in the OpenGroup POSIX documentation, so it looks like it is a Linux extension... but since supporting it means passing Lua strings around correctly I'm not opposed to including it.

I reworked your patch a little, and made sure we have symmetry between `pushsockaddrinfo` (used by `getaddrinfo`, `getsockname`,  `accept`, etc) and `sockaddr_from_lua` (for `bind`, `connect` etc), so that both client and server can be written in Lua.

Does this work for you?  Since I can't test it, nor add it to the specs portably... I wonder if you could write a minimal client and server for inclusion in the shipped examples that I can push at the same time?

Cheers,
Gary

```diff
diff --git a/ext/include/_helpers.c b/ext/include/_helpers.c
index 48a33bc..cd45da6 100644
--- a/ext/include/_helpers.c
+++ b/ext/include/_helpers.c
@@ -309,14 +309,15 @@ checknumberfield(lua_State *L, int index, const char *k)
 }
 
 static const char *
-checkstringfield(lua_State *L, int index, const char *k)
+checklstringfield(lua_State *L, int index, const char *k, size_t *plen)
 {
 	const char *r;
 	checkfieldtype(L, index, k, LUA_TSTRING, NULL);
-	r = lua_tostring(L, -1);
+	r = lua_tolstring(L, -1, plen);
 	lua_pop(L, 1);
 	return r;
 }
+#define checkstringfield(L,i,s) (checklstringfield(L,i,s,NULL))
 
 static int
 optintfield(lua_State *L, int index, const char *k, int def)
@@ -407,6 +408,13 @@ binding_notimplemented(lua_State *L, const char *fname, const char *libname)
 	}								\
 } LPOSIX_STMT_END
 
+#define pushlstringfield(k,v,l) LPOSIX_STMT_BEG {			\
+	if (l > 0 && v) {						\
+		lua_pushlstring(L, (const char *) v, (size_t) l);	\
+		lua_setfield(L, -2, k);					\
+	}								\
+} LPOSIX_STMT_END
+
 #define pushliteralfield(k,v) LPOSIX_STMT_BEG {				\
 	if (v) {							\
 		lua_pushliteral(L, v);					\
diff --git a/ext/posix/sys/socket.c b/ext/posix/sys/socket.c
index 1332091..e1c5b5f 100644
--- a/ext/posix/sys/socket.c
+++ b/ext/posix/sys/socket.c
@@ -76,8 +76,6 @@ static int
 pushsockaddrinfo(lua_State *L, int family, struct sockaddr *sa)
 {
 	char addr[INET6_ADDRSTRLEN];
-	struct sockaddr_in *sa4;
-	struct sockaddr_in6 *sa6;
 
 	lua_newtable(L);
 	pushintegerfield("family", family);
@@ -85,25 +83,35 @@ pushsockaddrinfo(lua_State *L, int family, struct sockaddr *sa)
 	switch (family)
 	{
 		case AF_INET:
-			sa4 = (struct sockaddr_in *)sa;
+		{
+			struct sockaddr_in *sa4 = (struct sockaddr_in *)sa;
 			inet_ntop(family, &sa4->sin_addr, addr, sizeof addr);
 			pushintegerfield("port", ntohs(sa4->sin_port));
 			pushstringfield("addr", addr);
 			break;
+		}
 		case AF_INET6:
-			sa6 = (struct sockaddr_in6 *)sa;
+		{
+			struct sockaddr_in6 *sa6 = (struct sockaddr_in6 *)sa;
 			inet_ntop(family, &sa6->sin6_addr, addr, sizeof addr);
 			pushintegerfield("port", ntohs(sa6->sin6_port));
 			pushstringfield("addr", addr);
 			break;
+		}
 		case AF_UNIX:
-			pushstringfield("path", ((struct sockaddr_un *) sa)->sun_path);
+		{
+			struct sockaddr_un *sau = (struct sockaddr_un *)sa;
+			pushlstringfield("path", sau->sun_path, sau->sun_len);
 			break;
+		}
 #if HAVE_LINUX_NETLINK_H
 		case AF_NETLINK:
-			pushintegerfield("pid", ((struct sockaddr_nl *) sa)->nl_pid);
-			pushintegerfield("groups", ((struct sockaddr_nl *) sa)->nl_groups);
+		{
+			struct sockaddn_nl *san = (struct sockaddr_nl *)sa;
+			pushintegerfield("pid", san->nl_pid);
+			pushintegerfield("groups", san->nl_groups);
 			break;
+		}
 #endif
 	}
 
@@ -223,12 +231,15 @@ sockaddr_from_lua(lua_State *L, int index, struct sockaddr_storage *sa, socklen_
 		case AF_UNIX:
 		{
 			struct sockaddr_un *sau	= (struct sockaddr_un *)sa;
-			const char *path	= checkstringfield(L, index, "path");
+			size_t len;
+			const char *path	= checklstringfield(L, index, "path", &len);
 
 			checkfieldnames (L, index, Safunix_fields);
 
+			if (len > sizeof(sau->sun_path)) len = sizeof(sau->sun_path);
+
 			sau->sun_family	= family;
-			strlcpy(sau->sun_path, path, sizeof(sau->sun_path));
+			memcpy(sau->sun_path, path, len);
 			sau->sun_path[sizeof(sau->sun_path) - 1]= '\0';
 			*addrlen	= sizeof(*sau);
 			r		= 0;
```

**Comment by essele** [comment]
Hi Gary,

> On 5 Oct 2015, at 00:56, Gary V. Vaughan <notifications@github.com> wrote:
> 
> I reworked your patch a little, and made sure we have symmetry between pushsockaddrinfo (used by getaddrinfo, getsockname, accept, etc) and sockaddr_from_lua (for bind, connect etc), so that both client and server can be written in Lua.
> 
Good catch .. I missed that completely.

> Does this work for you? Since I can't test it, nor add it to the specs portably... I wonder if you could write a minimal client and server for inclusion in the shipped examples that I can push at the same time?
> 
It looks good, I will test this evening and put together some examples for you.

One comment: if you are happy that the zero terminator is covered by sa being zero'd up front (as is the case where the string is shorter) then you could eliminate the line that adds the zero at the end of sau->sun_path by changing the length check slightly:

If (len >= sizeof(sau->sun_path)) len = sizeof(sau->sun_path)-1;

That should ensure the zero byte remains at the end regardless of the passed string size.

Cheers,

Lee.

**Comment by gvvaughan** [comment]
Any progress?

**Comment by essele** [comment]
Hi Gary,

> On 13 Oct 2015, at 03:45, Gary V. Vaughan <notifications@github.com> wrote:
> 
> Any progress?
> 
Yes, sorry for the delay, I did these a while ago, but other things got in the way… they are a very simple client/server pair that uses abstract sockets. I’m not sure how you want to represent the posix requires .. I either use the below or have more complex scripts use a metatable to ‘autoload’, I guess for simple examples a normal set of require’s might be more appropriate.

They are not elegant or particularly advanced, they just show the basic function of a datagram abstract socket.

Cheers,

Lee.



The client…

#!/usr/bin/lua

-- Require all the relevant bits of the posix library
local posix = {
	sys = { socket = require("posix.sys.socket") },
	unistd = require("posix.unistd"),
}

-- Create an AF_UNIX datagram socket
local s = posix.sys.socket.socket(posix.sys.socket.AF_UNIX, posix.sys.socket.SOCK_DGRAM, 0)

-- Sendto will use the sbtract AF_UNIX name "mysocket"
local daddr = {
		family = posix.sys.socket.AF_UNIX,
		path = "\0mysocket",
}

local rc, err = posix.sys.socket.sendto(s, arg[1] or "test data", daddr)
if not rc then error(err) end



The server…

#!/usr/bin/lua

-- Require all the relevant bits of the posix library
local posix = {
	sys = { socket = require("posix.sys.socket") },
	unistd = require("posix.unistd"),
}

-- Create an AF_UNIX datagram socket
local s = posix.sys.socket.socket(posix.sys.socket.AF_UNIX, posix.sys.socket.SOCK_DGRAM, 0)

-- Bind to the sbtract AF_UNIX name "mysocket"
local laddr = {
		family = posix.sys.socket.AF_UNIX,
		path = "\0mysocket",
}

local rc = posix.sys.socket.bind(s, laddr)
assert(rc==0, "unable to bind()")

-- Receive datagrams on the socket and print out the contents
while(1) do
		local dg = posix.sys.socket.recv(s, 1024)
		print("Got packet: ["..tostring(dg).."]")
end

**Comment by gvvaughan** [comment]
Hi Lee,

That's perfect.  I'll tidy them up and push to master, and ping you for a quick check that I didn't break anything.

Thank you!

**Comment by gvvaughan** [comment]
Hi Lee,

I reformatted you examples and committed along with my diff from above.  Please let me know if you find any problems with this.

Cheers,
Gary
