### ISSUE TITLE
popen/pclose missing? 

### ISSUE THREAD

**Issue by mkschreder** [luaposix/luaposix#235]
I found this: 

- New functions `popen`, `popen_pipeline` and `pclose` mimic the POSIX
    functions of the same name while allowing tasks to be Lua functions.

Unfortunately I can not find these functions anywhere. I can not use io.popen because corresponding close method does not return process return value and instead just returns true or false. 

Using your library, how can run a command, capture stdout (and also preferably stderr) as well as return value of the process once it exits? Is there an example somewhere?

**Comment by gvvaughan** [comment]
This is becoming a FAQ, so I'll add the following code to the examples directory before the next release.

Just as you would with the POSIX apis in C:

```lua
local unistd = require "posix.unistd"
local sys_wait = require "posix.sys.wait"

local stdout_r, stdout_w = unistd.pipe ()
assert (stdout_r ~= nil, stdout_w)

local stderr_r, stderr_w = unistd.pipe ()
assert (stderr_r ~= nil, stderr_w)

local pid, errmsg = unistd.fork ()
assert (pid ~= nil, errmsg)

if pid == 0 then
  unistd.close (stdout_r)
  unistd.close (stderr_r)

  unistd.dup2 (stdout_w, unistd.STDOUT_FILENO)
  unistd.dup2 (stderr_w, unistd.STDERR_FILENO)

  -- Exec() a subprocess here instead if you like --

  io.stdout:write "output string"
  io.stderr:write "oh noes!"
  os.exit (42)
end

unistd.close (stdout_w)
unistd.close (stderr_w)

local outs, errmsg = unistd.read (stdout_r, 1024)
assert (outs ~= nil, errmsg)
print ("STDOUT:", outs)

local errs, errmsg = unistd.read (stderr_r, 1024)
assert (errs ~= nil, errmsg)
print ("STDERR:", errs)

local pid, reason, status = sys_wait.wait (pid)
assert (pid ~= nil, reason)
print ("child " .. reason, status)
```

@rrthomas wrapped the low-level calls I used above to make convenient `posix.popen` functions et. al.  But some distributions are apparently no longer shipping the Lua part of luaposix :-o

I notice that the documentation of those functions did not make in into the publish HTML output for the last release.  I'll fix that before the next release.

**Comment by gvvaughan** [comment]
Correction, `posix.pclose`, `posix.popen` and `posix.popen_pipeline` are documented properly right here: http://luaposix.github.io/luaposix/modules/posix.html#pclose
