### ISSUE TITLE
Wrong in docs for dir.lua

### ISSUE THREAD

**Issue by mkschreder** [luaposix/luaposix#237]
http://luaposix.github.io/luaposix/examples/dir.lua.html#

Says it returns "ok, files". When in reality it includes "files, status"..

**Comment by gvvaughan** [comment]
the `ok` reflects whether `pcall` succeeded, and `status` is not assigned to a local because it is not used by the rest of the code; everything looks good to me as it is.

**Comment by mkschreder** [comment]
Right ok. I was actually calling dir directly so I did not get the ok as
you did.
