### ISSUE TITLE
error: can't build i686-pc-cygwin shared library unless -no-undefined is specified

### ISSUE THREAD

**Issue by bunster** [luaposix/luaposix#243]
Hello. I'm trying to build luaposix on my WIndows machine using the Babun terminal (which uses cygwin). When it gets to the make file, it fails with the above error. I uploaded the [entire log](http://pastebin.com/WWT86HuU) to Pastebin... Any ideas?

**Comment by gvvaughan** [comment]
Hi Jonathan,

Yes.  From https://www.gnu.org/software/libtool/manual/html_node/Inter_002dlibrary-dependencies.html:

> Some platforms, such as Windows, do not even allow you this flexibility. In order to build a shared library, it must be entirely self-contained or it must have dependencies known at link time (that is, have references only to symbols that are found in the .lo files or the specified ‘-l’ libraries), and you need to specify the -no-undefined flag. By default, libtool builds only static libraries on these kinds of platforms.

You'll also hit this issue from https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html:

> ‘win32-dll’
> This option should be used if the package has been ported to build clean dlls on win32 platforms. Usually this means that any library data items are exported with __declspec(dllexport) and imported with __declspec(dllimport). If this macro is not used, libtool will assume that the package libraries are not dll clean and will build only static libraries on win32 hosts.
> 
> Provision must be made to pass -no-undefined to libtool in link mode from the package Makefile. Naturally, if you pass -no-undefined, you must ensure that all the library symbols really are defined at link time!

You can try running `./configure` as normal and then running `make LDFLAGS=-no-undefined` to pass that flag to libtool link-mode, however the Makefile is designed for Unix style linkers where it's possible to make a shared luaposix.so module that has references to symbols from the shared lua library that are not resolved at compile time, but by the dynamic loader as the application loads libraries.  I expect passing -no-undefined will complain that all the liblua symbols are undefined.  You might be try to add -llua too, though I have no idea whether that will work (it might, but the binary format and DLL rules on Windows are weird and confusing, so it might not).  Some people create stub libraries to satisfy the missing symbols, where the stub functions will look up the real symbol in the target DLL at runtime and call that.  I understand there might also be some magic you can perform with linker scripts.

Another, easier, way is to proceed is to statically link a custom lua binary with luaposix sources preloaded.  That will be much easier to get working, but doesn't help much if you were hoping for a runtime loadable luaposix.dll.

Once you've fought your way through that minefield, please be aware luaposix makes no attempt to patch-up missing or buggy POSIX API implementations in the host library though, so I would be (pleasantly) surprised to hear that luaposix is even approaching well behaved with cygwin if you get it all to build and run.

HTH!

**Comment by cxw42** [comment]
@gvvaughan Thanks for the tip on the `LDFLAGS`!

Here's what worked for me, for the benefit of future readers:

 1. `luarocks download luaposix`
 1. `luarocks unpack luaposix`
    
    You will get a message similar to:

        You may now enter directory
        luaposix-33.4.0-1/luaposix-release-v33.4.0
        and type 'luarocks make' to build.

 1. `cd luaposix-33.4.0-1/luaposix-release-v33.4.0` (or whatever directory it told you)
 1. Edit the `.rockspec` file in that directory, e.g., `luaposix-33.4.0-1.rockspec`
 1. In the `build` section, edit the `build_command` string.  Where it says

        ./configure <lots of stuff> && make clean install

    change that to 

        ./configure <all the same stuff> && make LDFLAGS='-no-undefined -llua' clean install

 1. Run `luarocks make`.
 1. You should (eventually) see something like `luaposix 33.4.0-1 is now installed in /usr/local (license: MIT/X11)`.
 1. To double-check, run `luarocks show luaposix`
