### ISSUE TITLE
LOG_AUTHPRIV, LOG_FTP not POSIX

### ISSUE THREAD

**Issue by wahern** [luaposix/luaposix#244]
Neither LOG_AUTHPRIV nor LOG_FTP are defined by POSIX.

Most systems provide them. However, luaposix fails to build on Solaris because they're defined in `<netinet/ip_compat.h>`, which is part of the IPF framework and not visible by default.

AIX defines LOG_AUTHPRIV but not LOG_FTP.

**Comment by gvvaughan** [comment]
Thanks for the report.  I don't have access to those systems, so please let me know if this doesn't work for you.
