### ISSUE TITLE
AIX doesn't have getopt.h or getopt_long

### ISSUE THREAD

**Issue by wahern** [luaposix/luaposix#245]
luaposix on AIX fails to build because it has neither getopt.h nor getopt_long. Neither of those are POSIX.

FWIW, getopt is declared in unistd.h according to POSIX, not getopt.h, and I've never seen a platform where that doesn't work. Where getopt_long is available, it's visible through unistd.h as well.

**Comment by wahern** [comment]
I was completely wrong about getopt_long being visible through unistd.h. It's the opposite--non-POSIX header getopt.h is required to see getopt_long declarations on all the platforms I tested.

**Comment by gvvaughan** [comment]
thanks for the update... I'll look for an alternative getopt_long library I can point people at and revert to using just the POSIX getopt APIs from luaposix.
