### ISSUE TITLE
undefined symbol: luaopen_posix

### ISSUE THREAD

**Issue by siddsghosh** [luaposix/luaposix#249]
## installed latest using luarocks under lua-5.3.3 but while loading posix I get:

require('posix')
error loading module 'posix' from file '/picnic/u/apps/la/opt/lua/5.3.3/gnu/4.8.5/lib/lua/5.3/posix.so':
    /picnic/u/apps/la/opt/lua/5.3.3/gnu/4.8.5/lib/lua/5.3/posix.so: undefined symbol: luaopen_posix
stack traceback:
    [C]: in ?
    [C]: in function 'require'
    stdin:1: in main chunk

**Comment by gvvaughan** [comment]
Sorry I missed this earlier.

It looks like your Lua installation is broken.  Are you installing the latest luarock?  Do other rocks load correctly?  Other rocks with a .so file?  Is the posix.so path you quote correct?  Does that file exist?  Does it have any luaopen_* symbols?  Is the path you quote listed in `package.cpath` when you start Lua from the command line?  What are the timestamps on the files you installed?

Running `require('posix')` with all the search paths set to match luarocks (`eval luarocks path`) should load the `posix/init.lua` file, which in turn pulls the submodules from the .so on demand according to the subtables you use from the `posix/init.lua` returned table.

HTH?
