### ISSUE TITLE
Missing .gitmodules?

### ISSUE THREAD

**Issue by sathieu** [luaposix/luaposix#250]
The following command fails:
```
$ LANG=C git submodule init
fatal: No url found for submodule path 'slingshot' in .gitmodules
```

**Comment by gvvaughan** [comment]
the `bootstrap` script takes care of this.

**Comment by sathieu** [comment]
OK. But this prevent using cmake to clone the repo.

**Comment by gvvaughan** [comment]
cloning the repo assumes you have all the tools needed to run bootstrap, and is more for people who want to contribute or test patches - if you just want to build and/or deploy as a loadable module, consider using one of the release tar balls where bootstrap has already run and the generated files and submodules have already been pulled in with matching and fully tested versions.

Cheers,
Gary
