### ISSUE TITLE
socket.getpeername()

### ISSUE THREAD

**Issue by Zash** [luaposix/luaposix#255]
A binding to `getpeername` would be a handy complement to `getsockname`.

**Comment by gvvaughan** [comment]
sounds good! Would you like to take a shot at making a patch?

**Comment by Zash** [comment]
Sure. I haven't found anything suggesting it needs anything but a copy of getsockname and `s/sock/peer/`, so should be simple.

**Comment by gvvaughan** [comment]
Good call.  Added NEWS, specl checks (after a fashion) and merged.  Much appreciated, thank you!
