### ISSUE TITLE
undefined symbol: luaL_setfuncs

### ISSUE THREAD

**Issue by srikanthbojja** [luaposix/luaposix#257]
/usr/bin/lua: error loading module 'posix.ctype' from file '/homeappl/home/njayavel/appl_taito/torch/install/lib/lua/5.3/posix.so':
	/homeappl/home/njayavel/appl_taito/torch/install/lib/lua/5.3/posix.so: undefined symbol: luaL_setfuncs
stack traceback:
	[C]: ?
	[C]: in function 'require'
	...ppl_taito/torch/install/share/lua/5.3/posix/init.lua:29: in main chunk
	[C]: in function 'require'
	.../lmod/5.9.4.1/lmod/lmod/libexec/../tools/fileOps.lua:35: in main chunk
	[C]: in function 'require'
	...ppl/opt/lmod/5.9.4.1/lmod/lmod/libexec/myGlobals.lua:40: in main chunk
	[C]: in function 'require'
	/appl/opt/lmod/5.9.4.1/lmod/lmod/libexec/lmod:69: in main chunk

**Comment by gvvaughan** [comment]
Sorry I didn't see this sooner.

A properly compiled lua53 library does provide luaL_setfuncs (as you can see by grepping it's sources), and a properly compiled posix.so for lua53 will satisfy that symbol from the lua library.

Did you recently upgrade your lua installation?  Did you recompile luaposix against the correct headers, and with the correct runtime link path?  Do you have any other installations of earlier lua releases that the luaposix compile could have mistakenly built against?  Did you build this yourself, or use luarocks, or use modules prebuilt by your distro?  Did you get a posix.so built from sources released after lua53 came out and compatibility was added?

Hopefully, finding the answers to those questions will help you find out where your installation is broken.
