### ISSUE TITLE
configure: error: not a Lua interpreter

### ISSUE THREAD

**Issue by agladysh** [luaposix/luaposix#258]
I'm getting this on my OS X 10.11.6 box when I type `sudo luarocks install luaposix` with luarocks 2.2.0.

```
checking if /usr/local/opt/lua/bin/lua5.2 is a Lua interpreter... no
configure: error: not a Lua interpreter

Error: Build error: Failed building.
```

```
$ ls /usr/local/opt/lua/bin/
lua	luac
```

```
$ lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```

```
$ luarocks help

LuaRocks 2.2.0, a module deployment system for Lua

NAME
	/usr/local/bin/luarocks - LuaRocks main command-line interface

<...>

CONFIGURATION
	Lua version: 5.1
	Configuration files:
		System: /usr/local/etc/luarocks/config-5.1.lua (ok)
		User  : /Users/agladysh/.luarocks/config.lua (not found)

	Rocks trees in use: 
		/Users/agladysh/.luarocks ("user")
		/usr/local ("system")
```

This is likely to be a misconfiguration on my end, but I am at loss as how to debug the luaposix build process. Please help.

**Comment by gvvaughan** [comment]
config.log will show a detailed output of all the commands configure has run on your machine, which should help you figure out where things have come off the rails. You might also try overriding the path to the Lua binary at configure time by setting 'LUA=/use/local/opt/lua/bin/lua'.

I would guess that either the Lua search is preferring a 5.2 interpreter it found over the 5.1 interpreter you were expecting? Or perhaps you don't have /usr/local/opt/lua/bin early enough (or at all?) in your command search path. I don't recall whether Windows uses $PATH like unix, sorry :-/

and finally, I have a patch queued to expunge autotools from the luaposix build entirely, so if all else fails waiting for that to land may save you from debugging your current issue.

**Comment by agladysh** [comment]
> config.log will show a detailed output of all the commands configure has run on your machine, which should help you figure out where things have come off the rails. 

Alas, LuaRocks does not let me view the temporary files during the build.

> You might also try overriding the path to the Lua binary at configure time by setting 'LUA=/usr/local/opt/lua/bin/ luarocks '.

```
$ export LUA=/usr/local/opt/lua/bin/lua
$ sudo luarocks install luaposix
```

The above fails in exactly the same way as before.

> I would guess that either the Lua search is preferring a 5.2 interpreter it found over the 5.1 interpreter you were expecting? 

To the best of my knowledge I do not have Lua 5.2 installed on this box.

If you will give me a hint how autotools picks Lua prefix, I will try to figure out what confuses it.

`sudo env | grep -i lua` yields empty result.

> Or perhaps you don't have /usr/local/opt/lua/bin early enough (or at all?) in your command search path. 

```
$ which lua
/usr/local/bin/lua
```

I do not know, frankly, what is `/usr/local/opt/lua/bin` on my machine (except that there is another copy of Lua 5.1 there for some reason) and how did configure find it... Probably a remainder of some older installation.

> I don't recall whether Windows uses $PATH like unix, sorry :-/

Not sure about Windows, I'm on OS X (which works with $PATH as expected).

> and finally, I have a patch queued to expunge autotools from the luaposix build entirely, so if all else fails waiting for that to land may save you from debugging your current issue.

Would be great. However, I'm stuck with 30.0 (later versions break my code by introducing a global variable), so the patch would not entirely help...

**Comment by agladysh** [comment]
Here is what I get by cloning the current git head and trying to make a rock manually:

```
$ sudo luarocks make luaposix-git-1.rockspec 
LUA='/usr/local/opt/lua/bin/lua5.2' ./bootstrap && ./configure LUA='/usr/local/opt/lua/bin/lua5.2' LUA_INCLUDE='-I/usr/local/opt/lua/include' --prefix='/usr/local/lib/luarocks/rocks/luaposix/git-1' --libdir='/usr/local/lib/luarocks/rocks/luaposix/git-1/lib' --datadir='/usr/local/lib/luarocks/rocks/luaposix/git-1/lua' --datarootdir='/usr/local/lib/luarocks/rocks/luaposix/git-1' && make clean all
bootstrap:   error: Prerequisite 'help2man' not found. Please install it, or
bootstrap:          'export HELP2MAN=/path/to/help2man'.
bootstrap:   error: Program    Min_version Homepage                            
bootstrap:          -----------------------------------------------------------
bootstrap:          git        -           http://git-scm.com                  
bootstrap:          help2man   1.29        http://www.gnu.org/s/help2man       
bootstrap:          automake   -           http://www.gnu.org/s/automake       
bootstrap:          libtoolize 2.2.6       http://www.gnu.org/s/libtool        
bootstrap:          -----------------------------------------------------------

Error: Build error: Failed building.
```

So, 5.2 is there somewhere indeed. Could be an installation problem for my LuaRocks...

**Comment by agladysh** [comment]
Ah, well, as I suspected, it is my old and broken homebrew installation. Thank you for the help!

**Comment by gvvaughan** [comment]
Happy that my straw clutching helped you find an answer to your immediate problem.

Would you please make another issue with the output and or test case for the global variable issue that is preventing you from following luaposix master?

Cheers,
Gary
