### ISSUE TITLE
documentation of posix.stat

### ISSUE THREAD

**Issue by hishamhm** [luaposix/luaposix#259]
Looking at http://luaposix.github.io/luaposix/modules/posix.sys.stat.html and comparing to the use of this function in the LuaRocks codebase, where there is a `posix.stat(filename, "mode")`, it seems that the documentation for the stat() function is incomplete, lacking the description of the second argument.

More notably, the results I get with the table results don't match the description of the [PosixStat](http://luaposix.github.io/luaposix/modules/posix.sys.stat.html#PosixStat) table:

```
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> posix = require ("posix")
> for k,v in pairs(posix.stat("xfce.txt")) do print(k,v) end
uid	1000
size	358
mtime	1410203604
type	regular
ino	3806959
nlink	1
dev	2052
ctime	1410203604
atime	1482868159
gid	100
mode	rw-r--r--
```

Notably, keys don't have a `st_` prefix as documented, and they are not all "int" (`mode` and `type` are strings, and `type` is not documented in PosixStat, so I don't know what are the possible values.

This is running the latest version:

```luarocks show luaposix --mversion
33.4.0-1
```

**Comment by gvvaughan** [comment]
`posix.stat` is the lua wrapper for `posix.sys.stat.stat`; where the latter is the new thin C only module that calls stat(2) and doesn't do any mangling of arguments or return values except as necessary to fit the Lua C API... and the former is a Lua wrapper for the latter to maintain legacy luaposix API compatibility.

The two are supposed to be different, but the LDocs do seem out of sync, thanks. I'll push a patch as soon as I get back to my computer.

**Comment by hishamhm** [comment]
Ah, thanks! I had just realized that `posix.sys.stat.stat` exists and behaves as documented. The documentation in the [main module](http://luaposix.github.io/luaposix/modules/posix.html) misled me to think it was a copy:

> In addition to the convenience functions documented in this module, all APIs from submodules are copied into the return table for convenience and backwards compatibility.

**Comment by hishamhm** [comment]
thanks!
