### ISSUE TITLE
Fails on build with Arch Linux

### ISSUE THREAD

**Issue by Dobbie03** [luaposix/luaposix#261]
I'm trying to build luaposix on my Arch setup but I get this error:

`==> Validating source files with md5sums...
    lua-posix ... Skipped
==> Extracting sources...
  -> Creating working copy of luaposix git repo...
Cloning into 'lua-posix'...
done.
==> Starting prepare()...
sed: can't read bootstrap.conf: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
==> ERROR: Makepkg was unable to build lua-posix-git.
==> Restart building lua-posix-git ? [y/N]
==> --------------------------------------
==> `

Any ideas what I should be doing?

**Comment by gvvaughan** [comment]
These messages don't come from luaposix; they are all from the distro packaging tools - you could ask on a list or forum dedicated to arch linux packaging.

Alternatively, and assuming you have a properly installed LuaRocks, following the install instructions in the luaposix README.md will work.

HTH,
Gary
