### ISSUE TITLE
no support for sysmsg.msgctl

### ISSUE THREAD

**Issue by zmlopez** [luaposix/luaposix#262]
I've used luaposix to create message queues and work fantastic, but by creating and deleting processes I ended up getting the message:
     error creating ipc msgget: No space left on device
It would be interesting to be able to delete created message queues, This would be done by the call:
    sysmsg.msgctl(id_procces, IPC_RMID, nil)
where IPC_RMID = 0
But it seems that the call msgctl is not available in luaposix.

**Comment by gvvaughan** [comment]
Hi, thanks for the report!

I'd be very happy to apply a patch implementing even a subset of msgctl API - would you be interested in writing it? The code should be very straight forward to derive from similar functions already implemented in luaposix, and I'd be delighted to answer any questions that come up...

**Comment by zmlopez** [comment]
Hi,

Thanks for the offer.
I was thinking about doing it but I've found a workaround by using ipcrm utility to remove ipc queues.

Writting the patch would take me too much time because I don't know the lua to c interface. Maybe in the future if I've managed to get enough time.

Regards
