### ISSUE TITLE
Wishlist: truncate(2) & ftruncate(2)

### ISSUE THREAD

**Issue by Zash** [luaposix/luaposix#263]
[`truncate(2)`](http://pubs.opengroup.org/onlinepubs/009695399/functions/truncate.html) and [`ftruncate(2)`](http://pubs.opengroup.org/onlinepubs/009695399/functions/ftruncate.html). Use cases include rolling back an append-write.

**Comment by gvvaughan** [comment]
Great idea! Can I interest you in making a pull-request?

**Comment by Zash** [comment]
Perhaps. Is `posix.unistd` the right place?
