### ISSUE TITLE
luke leaves temporary files behind

### ISSUE THREAD

**Issue by Zash** [luaposix/luaposix#264]
`os.tmpname()`, used by the `spawn()` function in `build-aux/luke`, creates the file whose name it returns, but the build system never deletes these temporary files. Thus after building, there are quite the number of files like `/tmp/lua_RanDOm` left behind.

**Comment by gvvaughan** [comment]
thanks for the report, I've been meaning to fix this and had forgotten it is still an issue... will try to get to it today
