### ISSUE TITLE
Question: Interop with Lua io lib file handles?

### ISSUE THREAD

**Issue by Zash** [luaposix/luaposix#266]
Is there some thought on how one should deal with Luas normal io lib file handles?

It's possible to extract the FD out of them, is this something that would be within scope to add?

**Comment by gvvaughan** [comment]
Lua file handles are an implementation detail, and as such extracting any field (including the underlying descriptor) requires different gymnastics for LuaJIT, and PUC Rio Lua --ISTR ithe memory layout of the handle structure even varies between PUC Rio's releases-- which, I think would make it an extraordinarily brittle feature to maintain, so I'm not keen to implement it here as luaposix is basically complete now, but for bug fixes and keeping up with the spec.

However, I do think the community would love to have a small module that abstracts over the differences between the implementations, so if you wanted to propose something outside of luaposix I'll bet it would get a very warm reception :-)

Incidentally, there is a gitter channel for luaposix for non-issue related stuff you might find more convenient than making issues in github...
