### ISSUE TITLE
Wrap getsockopt?

### ISSUE THREAD

**Issue by CMB** [luaposix/luaposix#267]
I wanted to be able to query SO_ERROR when making a non-blocking
connect() call, but I found that getsockopt hasn't been wrapped.
Is it just the case that no one has needed it or been
interested in writing it?  Or is there a technical
reason for excluding it?
If it's the former, I'm more than willing to do the work
and send up a PR.

**Comment by gvvaughan** [comment]
Yep, purely that no one has needed it so far. I'd be delighted to take your PR, thanks!
