### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by raingloom** [luaposix/luaposix#272]
As someone who doesn't use the POSIX C API at all I am at a complete loss as to what `posix.getopt` actually returns, what are the 4 values I am expecting?

I'd volunteer but as I said I don't know the C APIs and I don't have time to get into them right now.

**Comment by gvvaughan** [comment]
Hi.  Thanks for your interest in luaposix. As a very thin wrapper around the posix API, I'm afraid that there's little option for you but to learn the posix API calls that you want to use; however, I've tried to provide enough pointers to make learning each call reasonably straight forward without trying to rewrite the SUSv3 documentation.

There is a small example in the comments above the code for getopt, repeated in the generated documentation, along with a pointer to a more complete example and deep links directly to the POSIX calls being wrapped:

  http://luaposix.github.io/luaposix/modules/posix.getopt.html

I'd be happy to take concrete suggestions for specific improvements if this is not enough to get you up and running.

HTH,
Gary
