### ISSUE TITLE
Install from luarocks is failing

### ISSUE THREAD

**Issue by wichtounet** [luaposix/luaposix#273]
Hi, 

I just tried to install this with luarocks on my Gentoo machine and it failed with the following messages: 

```
libtool: install: /usr/bin/install -c ext/posix/.libs/posix.so /home/wichtounet/torch/install/lib/luarocks/rocks/luaposix/33.4.0-1/lib/posix.so
/usr/bin/install: cannot stat 'ext/posix/.libs/posix.so': No such file or directory
```

Is there something missing on my system ? 

Thanks

**Comment by gvvaughan** [comment]
It looks like you're missing some or all of the toolchain for compiling since the luaposix library did not get built.  There are probably some useful error messages further back in your terminal that will tell what went wrong... there's not really much to go on in what you pasted.
