### ISSUE TITLE
Unable to catch ctrl c , or explicit SIGINT

### ISSUE THREAD

**Issue by itsindra** [luaposix/luaposix#274]
I initially was trying to catch crtl c assuming it is SIGINT, but then i said let me just set an exit handler and print the return code and exit
```
posix = require "posix"
signal = require "posix.signal"

exit_method = function(num)
    print("ok exiting " .. tostring(num) .. "\n")
    os.exit(num)
end

for k,v in pairs(signal) do
    if type(v) == "number" then
        print (k,v)
    else
        print(k, type(v))
    end
end

for k,v in pairs(signal) do
    if v ~= nil and type(v) == "number" then
        signal.signal(v, exit_method)
    end
end
```

signal.raise(signal.SIGINT) 

I get the output 

> stdin:1: interrupted!
> stack traceback:
> 	[C]: in function 'raise'
> 	stdin:1: in main chunk
> 	[C]: ?

When i hit Ctrl + C it just exits without any message.  If i explicitly raise any other signal it works other (not tested exhaustively). 
My Lua version is 5.1.5 and am running on ubuntu 16.04. 

Also, when i check the return code in the shell its 130 . I even tried setting it explicitly for 130 by `signal.signal(130, exit_method)` and then CTRL + C , but that did not work either.

**Comment by gvvaughan** [comment]
Are you running your code with the standard interpreter?  `lua.c` in those sources sets up its own handling for SIGINT, so you'll need to recompile with that disabled if you plan on using your own SIGINT signal handler instead (whether by installing it with luaposix, or from a C module of your own).

**Comment by itsindra** [comment]
Got it.  Didn't realize that earlier. Thanks

**Comment by gvvaughan** [comment]
no worries, glad to help :-)
