### ISSUE TITLE
When building, CFLAGS, LDFLAGS, etc are not handled correctly if their values contain equals signs.

### ISSUE THREAD

**Issue by CMB** [luaposix/luaposix#278]
I filed a pull request and issue for this with the luke repo:
https://github.com/gvvaughan/luke/pull/1
But I figured I'd open an issue here, too, just in case someone
else tries to build and wonders why their CFLAGS / LDFLAGS aren't
being used.

**Comment by gvvaughan** [comment]
Thanks for the report and this issue, I merged the luke PR, along with an additional fix that came to light from the 34.0 porto-release.

There's another bug that prevents the 34.0-1 luarock I uploaded from building on macOS that I need to fix too, and then I'll resync luaposix' luke with the upstream repo and try again.
