### ISSUE TITLE
Install on RHEL 7.3

### ISSUE THREAD

**Issue by zqmuser** [luaposix/luaposix#281]
luaposix 33.4.0 (or a number of other versions) would not install via Luarocks using Lua 5.3.4 and Luarocks 2.4.2 on a system running RHEL 7.3.  The issue is an incompatibility with gcc versions that reserve the directory name "specs" for use by the compiler.  Here is my work around for manual install, which could be easily updated in the code.

Download a luaposix tar file from github
untar it
module load automake
mv specs yaml_specs
export LUA_INCLUDE=-I/opt/asn/apps/lua_5.3.4/include
./configure --prefix=/opt/asn/apps/lua_5.3.4
edit Makefile to change /specs/ to /yaml_specs/
make >&make.log1
make test
make install

**Comment by gvvaughan** [comment]
This looks very much like a misconfigured gcc install to me.  Having gcc look for a specs file in the current directory is almost as much of a security problem as having '.' in your PATH - a malicious person could easily put something in repository you are going to check out, and then you end up running it accidentally, with permissions to access all your files.  Imagine that I left an actual gcc specs file in the top of the luaposix tree that injected an additional library into your link line that you then installed into /usr/local as root...

I don't plan to rename the specs directory in all my Lua projects, but especially not if it helps a few people find a security issue with their installation that needs fixing.
