### ISSUE TITLE
_POSIX_TIMERS vs _XOPEN_REALTIME

### ISSUE THREAD

**Issue by karlp** [luaposix/luaposix#295]
I don't think your use of XOPEN_REALTIME to define the availability of clock_gettime() and friends is correct.  (ext/posix/time.c)

I can't find it anywhere in http://pubs.opengroup.org/onlinepubs/9699919799/functions/clock_gettime.html nor does http://pubs.opengroup.org/onlinepubs/7908799/xsh/feature.html imply that this is what XOPEN_REALTIME is for at all.

I believe these should be included if POSIX_TIMERS is defined instead.  XOPEN_REALTIME _includes_ POSIX_TIMERS, but you can have POSIX_TIMERS without all of XOPEN_REALTIME.

This is causing the clock_* functions to be missing on musl-libc builds

Potentially they could be XOPEN_REALTIME _or_ POSIX_TIMERS > 200809 or something?
https://linux.die.net/man/7/posixoptions implies that POSIX_TIMERS has covered this from 2001 as well.

**Comment by gvvaughan** [comment]
Thanks for all the links.  Having read these, I agree with you, and will update luaposix accordingly.
