### ISSUE TITLE
Custom named lua symbols .so librlua instead of liblua

### ISSUE THREAD

**Issue by TheBestJohn** [luaposix/luaposix#296]
I'm trying to build this on my target system but liblua.so has been renamed with the package I'm using. Instead I need to link librlua.so for the base lua symbols. 

with a makefile this is pretty straightforward. I just add a -lrlua and make sure it's in my -L path. How the heck do I do it with luke?

**Comment by gvvaughan** [comment]
Why are you linking against liblua at all?  Missing symbols will be resolved when the lua binary loads the posix module using the symbols it already has loaded from liblua.

Here's a sample module linked by travis before passing all the self tests:

```bash
cc -O2 -fPIC -shared   -D_XOPEN_SOURCE=700 -DVERSION='"git-1"' -DNDEBUG -D_FORTIFY_SOURCE=2 -D_POSIX_C_SOURCE=200809L -DPACKAGE='"luaposix"' -Iext/include -I/home/travis/build/luaposix/luaposix/here/include ext/posix/sys/stat.c -o linux/posix/sys/stat.so 
```
