### ISSUE TITLE
Documentation about unistd.execp is wrong about shell

### ISSUE THREAD

**Issue by socketpair** [luaposix/luaposix#302]
It actually does not use shell, as well as `unistd.exec`.

**Comment by socketpair** [comment]
luaposix code:
`(use_shell ? execvp : execv) (path, argv);`

Neither execvp nor execv use shell. So all cases when shell is mentioned are wrong.

**Comment by gvvaughan** [comment]
I clarified the docs not to conflate shell path splitting, and shell PATH searching.
