### ISSUE TITLE
Missing documentation for bunch of functions from posix.time

### ISSUE THREAD

**Issue by socketpair** [luaposix/luaposix#308]
at least:
```
gmtime()
clock_gettime()
strptime()
mktime()
time()
strftime()
localtime()
clock_getres()
nanosleep()
```

as well as constants:
```
CLOCK_MONOTONIC
CLOCK_PROCESS_CPUTIME_ID
CLOCK_THREAD_CPUTIME_ID
CLOCK_REALTIME
```

`gettimeofday()` is deprecated actually.

**Comment by gvvaughan** [comment]
I see docs for everything in your list here:

http://luaposix.github.io/luaposix/modules/posix.time.html

Although the usage of the constants could be better than buried in the functions that can take them.

**Comment by socketpair** [comment]
Damn! Confused posix.time and posix.sys.time
