### ISSUE TITLE
luaposix seems to be crashing my app

### ISSUE THREAD

**Issue by karai17** [luaposix/luaposix#312]
https://github.com/karai17/lapis-chan/issues/57

https://github.com/luaposix/luaposix/blob/1332cd1452f48b2dfc3b2d5c8a724c16d720a37d/lib/posix/deprecated.lua#L300

**Comment by gvvaughan** [comment]
Took a bit more fiddling to get it right than I had expected, but got there in the end :)
Thanks for catching the error!

**Comment by karai17** [comment]
It looks like there is another related issue~

https://github.com/karai17/lapis-chan/issues/57#issuecomment-419765383
