### ISSUE TITLE
Any way to set custom SYSLOG TAG for posix.syslog?

### ISSUE THREAD

**Issue by markus9203902** [luaposix/luaposix#317]
Hello.
For instance, 
os.execute("logger -p local0.info -t url-filter-subsystem -u /run/systemd/journal/dev-log" .. logstring )

will allow to change the TAG of syslog record to "url-filter-subsystem". For instance, in syslog an example of TAG is **snmpd[29384]** in this record:
_Nov 27 01:49:12 fw01 snmpd[29384]: error on subcontainer 'ia_addr' insert (-1)_

So it's just a name of process/PID what executed the script. 

In case of posix.syslog, it always LUA or LUA pid, but I want to customize it. 

Are there any ways to do this wit posix.syslog? 
I wasn't able to find any additional ways to pas parameters to
_posix.syslog(posix.LOG_LOCAL1, 'test lua log string one two three')_
in order to customize the tag.

**Comment by gvvaughan** [comment]
Actually `posix.syslog` is not a module I have used in my own code, but it is little more than a very thin wrapper around the POSIX C API documented fully here:

  http://pubs.opengroup.org/onlinepubs/9699919799/functions/syslog.html

Looking very superficially at your request, it seems like you would need to write a slightly higher level wrapper API to manage the arguments and splice them into the actual message string argument for syslog - I don’t know whether the logger command you cite is built with the posix syslog call, but if so you could port its implementation to Lua.

HTH,
Gary

**Comment by markus9203902** [comment]
> Actually `posix.syslog` is not a module I have used in my own code, but it is little more than a very thin wrapper around the POSIX C API documented fully here:
> 
> http://pubs.opengroup.org/onlinepubs/9699919799/functions/syslog.html
> 
> Looking very superficially at your request, it seems like you would need to write a slightly higher level wrapper API to manage the arguments and splice them into the actual message string argument for syslog - I don’t know whether the logger command you cite is built with the posix syslog call, but if so you could port its implementation to Lua.
> 
> HTH,
> Gary

Thank you for the comment, I'll dig into the logger command code.

**Comment by markus9203902** [comment]
UPD I found solution using the https://github.com/ntd/luasyslog module.
Just customize the syslog(name) **name** string.

```
local syslog = require 'logging.syslog'

local logger = syslog('luasyslog1')
logger:debug('Debug message new')
```

_Nov 27 16:55:18 fw01 luasyslog1[40922]: Debug message new_

**Comment by gvvaughan** [comment]
looking at the C code for that module, I think you can do the same thing with luaposix:

```
local syslog = require ‘posix.syslog’
syslog.openlog(‘luasyslog1’, syslog.LOG_PID)
syslog.syslog(syslog.LOG_DEBUG, ‘New debug log message’)
syslog.closelog()
```
