### ISSUE TITLE
Build failure, luaposix requires luke but not found

### ISSUE THREAD

**Issue by lhorace** [luaposix/luaposix#320]
Hello,

I running into trouble building `luaposix` with `luarocks`. See below:
https://github.com/lhorace/postgres-auth-server

`luarocks --lua-dir=/opt/openresty-rtmp/luajit --tree=lua_modules install --only-deps /opt/postgres-auth-server/rockspecs/postgres-auth-server-dev-1.rockspec`
```
/opt/openresty-rtmp/luajit/bin/luajit build-aux/luke package="luaposix" version="34.0.3" PREFIX="/opt/postgres-auth-server/lua_modules/lib/luarocks/rocks-5.1/luaposix/34.0.3-1" LUA="/opt/openresty-rtmp/luajit/bin/luajit" LUA_INCDIR="/opt/openresty-rtmp/luajit/include" CFLAGS="-O2 -fPIC" LIBFLAG="-shared" LIB_EXTENSION="so" OBJ_EXTENSION="o" INST_LIBDIR="/opt/postgres-auth-server/lua_modules/lib/luarocks/rocks-5.1/luaposix/34.0.3-1/lib" INST_LUADIR="/opt/postgres-auth-server/lua_modules/lib/luarocks/rocks-5.1/luaposix/34.0.3-1/lua"
/opt/openresty-rtmp/luajit/bin/luajit: build-aux/luke:654: module 'luke' not found:No LuaRocks module found for luke
stack traceback:
        [C]: in function 'require'
        build-aux/luke:654: in main chunk
        [C]: at 0x55e60a8ee310

Error: Failed installing dependency: https://luarocks.org/luaposix-34.0.3-1.src.rock - Build error: Failed building.
```

I found a reference to this problem [here](https://github.com/gvvaughan/lyaml/issues/22), however I don't know how to implement the suppose fix here https://github.com/gvvaughan/lyaml/issues/22#issuecomment-339833301 ?

OS: Ubuntu 18.04
Lua 5.1.5
Luarocks 3.0.4

P.S. Downgrading to `34.0.1-1` seems to fix building for me.

regards

**Comment by gvvaughan** [comment]
The fix described there is to unset LUA_INIT when calling luarocks - i.e.:

    LUA_INIT= luarocks install luaposix

I should come up with a wrapper for require inside luke to prevent tripping over this though. I'll see what I can do this weekend.

**Comment by jprjr** [comment]
Just thought I'd throw in, I've usually installed luarocks as a rock, using `make bootstrap`

It seems like in this mode, using `LUA_INIT=` has no effect. However, if I install luarocks using `make install`, I'm able to build `luaposix` without any problems, I don't need to unset `LUA_INIT=`

**Comment by MisterDA** [comment]
I still have this bug with master.
Unsetting `LUA_INIT` did not change anything.

```
$ luarocks install http://raw.github.com/luaposix/luaposix/master/luaposix-git-1.rockspec

/usr/bin/lua5.3 build-aux/luke package="luaposix" version="git" PREFIX="~/.local/lib/luarocks/rocks-5.3/luaposix/git-1" LUA="/usr/bin/lua5.3" LUA_INCDIR="/usr/include" CFLAGS="-O2 -fPIC" LIBFLAG="-shared" LIB_EXTENSION="so" OBJ_EXTENSION="o" INST_LIBDIR="~/.local/lib/luarocks/rocks-5.3/luaposix/git-1/lib" INST_LUADIR="~/.local/lib/luarocks/rocks-5.3/luaposix/git-1/lua"
/usr/bin/lua5.3: build-aux/luke:658: module 'luke' not found:No LuaRocks module found for luke
stack traceback:
	[C]: in function 'require'
	build-aux/luke:658: in main chunk
	[C]: in ?

Error: Build error: Failed building.
```

Thanks !

**Comment by 4mig4** [comment]
I have the same problem on FreeBSD 12.0-RELEASE 

my luarocks is installed as a rock ( ie: using make bootstrap)

```
luarocks list

Rocks installed for Lua 5.1
---------------------------

luarocks
   3.0.4-1 (installed) - /usr/local/lib/luarocks/rocks-5.1
```
Trying install luaposix yields:

```
luarocks install luaposix

Installing https://luarocks.org/luaposix-34.0.4-1.src.rock

/usr/local/bin/lua51 build-aux/luke package="luaposix" version="34.0.4" PREFIX="/usr/local/lib/luarocks/rocks-5.1/luaposix/34.0.4-1" LUA="/usr/local/bin/lua51" LUA_INCDIR="/usr/local/include/lua51" CFLAGS="-O2 -fPIC" LIBFLAG="-shared" LIB_EXTENSION="so" OBJ_EXTENSION="o" INST_LIBDIR="/usr/local/lib/luarocks/rocks-5.1/luaposix/34.0.4-1/lib" INST_LUADIR="/usr/local/lib/luarocks/rocks-5.1/luaposix/34.0.4-1/lua"
/usr/local/bin/lua51: build-aux/luke:658: module 'luke' not found:No LuaRocks module found for luke
stack traceback:
	[C]: in function 'require'
	build-aux/luke:658: in main chunk
	[C]: ?

Error: Failed installing dependency: https://luarocks.org/luaposix-34.0.4-1.src.rock - Build error: Failed building.
```

**Comment by 4mig4** [comment]
I have now this problem in Linux Ubuntu 18.04.3

**Comment by gvvaughan** [comment]
There appears to be a conflict between how a `make bootstrap` luarocks overrides `require` and how luke preloads modules in a single file. (@hishamhm FYI)

While I work out the details and figure out where a patch belongs, you can work around this by uninstalling your luarocks and reinstalling without bootstrap: `make install`

**Comment by martin-eden** [comment]
Problem is in minified `./build-aux/luke`. 

Downgrading `luaposix` to `33.4.0` worked for me.

OS Ubuntu 14.04
Lua 5.3.4
Luarocks dev-1

**Comment by 4mig4** [comment]
Is there any progress that would not have been pushed here ?

**Comment by gvvaughan** [comment]
The latest release fixes this issue AFAICT.

**Comment by 4mig4** [comment]
Upgrade worked fine, thanks a lot for fixing this :)
