### ISSUE TITLE
does  recv() return a string or an int ?

### ISSUE THREAD

**Issue by peterbillam** [luaposix/luaposix#322]
In
http://luaposix.github.io/luaposix/modules/posix.sys.socket.html#recv
it says:
  Returns:
  (int) received bytes, if successful

but when I run it (on a AF_UNIX socket)
recv returns a string, not an int...

**Comment by gvvaughan** [comment]
Looking at the source, it returns a string for sure.

Documentation bug, thanks for catching it!
