### ISSUE TITLE
Dependency on std.normalize not fully removed

### ISSUE THREAD

**Issue by mm-pagely** [luaposix/luaposix#324]
I see there was a [commit](https://github.com/luaposix/luaposix/commit/fb5c4e02e5166cdb2a2ec158431b39b9c1c59eeb) to remove `std.normalize` as a dep, but it doesn't look to be fully removed.  As of 34.1, `compat.lua` still attempts to require that library:

https://github.com/luaposix/luaposix/blob/v34.1/lib/posix/compat.lua#L15
https://github.com/luaposix/luaposix/commit/fb5c4e02e5166cdb2a2ec158431b39b9c1c59eeb#diff-a4e65afa9632517eeb9f34c68ceb5843L15

This is breaking installs from luarocks that aren't pinned to <34.1 for any systems that don't have `std.normalize` installed from a previous version of luaposix.

## to reproduce

(`test.lua`):
```lua
require 'posix'
```

```
$ luarocks install luaposix > /dev/null
$ lua test.lua
lua: /usr/local/share/lua/5.1/posix/compat.lua:15: module 'std.normalize' not found:
        no field package.preload['std.normalize']
        no file './std/normalize.lua'
        no file '/usr/local/share/lua/5.1/std/normalize.lua'
        no file '/usr/local/share/lua/5.1/std/normalize/init.lua'
        no file '/usr/local/lib/lua/5.1/std/normalize.lua'
        no file '/usr/local/lib/lua/5.1/std/normalize/init.lua'
        no file '/usr/share/lua/5.1/std/normalize.lua'
        no file '/usr/share/lua/5.1/std/normalize/init.lua'
        no file './std/normalize.so'
        no file '/usr/local/lib/lua/5.1/std/normalize.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/std/normalize.so'
        no file '/usr/lib/lua/5.1/std/normalize.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './std.so'
        no file '/usr/local/lib/lua/5.1/std.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/std.so'
        no file '/usr/lib/lua/5.1/std.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/share/lua/5.1/posix/compat.lua:15: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/posix/init.lua:333: in main chunk
        [C]: in function 'require'
        test.lua:1: in main chunk
        [C]: ?
```

**Comment by mm-pagely** [comment]
Looks like the test/build process installs `typecheck` via luarocks, which itself pulls in the missing `std.normalize` dependency:

```
$ luarocks show typecheck

[...]

Depends on:
        lua >= 5.1, < 5.4 (using 5.3-1)
        std.normalize >= 2.0.1 (using 2.0.2-1)
```

Hopefully that saves some duplicate effort and head-scratching to answer "why doesn't this blow up in CI if it's completely broken on install?" :)

I'm not familiar enough with lua dev to push a quick fix for this, but if I have the bandwidth later on I'll give it a shot (unless somebody else gets to it first).

**Comment by gvvaughan** [comment]
Nice catch, thank you.  I made a new release to fix this issue today.
