### ISSUE TITLE
localtime returns wrong when the year is larger than 2038

### ISSUE THREAD

**Issue by lcy03406** [luaposix/luaposix#325]
e.g. 2845213200 is 2060-02-29 1:0:0 and localtime should return tm_year==160 but it returns tm_year==24

**Comment by GReagle** [comment]
This is the year 2038 problem (see https://en.wikipedia.org/wiki/Year_2038_problem).  On my system, which is x86_64 GNU/Linux, a C program does not have this problem, but a Lua program does.

Here is a C script:
```
#!/usr/bin/tcc -run

#include <stdio.h>
#include <time.h>

int main (int argc, char ** argv)
{
	time_t sec;
	struct tm *t;

	sec = 2147483647;
	t = gmtime(&sec);
	printf("%ld seconds --> %i years \n", sec, t->tm_year);

	sec = 2147483648;
	t = gmtime(&sec);
	printf("%ld seconds --> %i years \n", sec, t->tm_year);
}
```
and its output is:

> 2147483647 seconds --> 138 years
> 2147483648 seconds --> 138 years

Here is a Lua program:
```
#!/usr/bin/env lua

pt=require 'posix.time'

sec = 2147483647
yrs = pt.gmtime(sec).tm_year
print(string.format("%i seconds --> %i years", sec, yrs))

sec = 2147483648
yrs = pt.gmtime(sec).tm_year
print(string.format("%i seconds --> %i years", sec, yrs))
```
and its ouput is

> 2147483647 seconds --> 138 years
> 2147483648 seconds --> 1 years
