### ISSUE TITLE
readlink() fails on /proc/[pid]/fd/[num]

### ISSUE THREAD

**Issue by overcrook** [luaposix/luaposix#328]
I came across a strange behavior of the readlink() call for symlinks inside the _/proc/[pid]/fd_ directory on a Linux system.

If the process has an open file descriptor for something other than a regular file (i.e. a socket, pipe), readlink() fails with the error "readlink wrote only N of 64 bytes".

This happens because the Linux kernel reports the size for all non-regular files as 64, but the readlink() call returns the actual length of the written content (and this may differ from 64).

An example on my system:

```
$ uname -a
Linux laptop17 5.6.12-1-MANJARO #1 SMP PREEMPT Sun May 10 14:36:43 UTC 2020 x86_64 GNU/Linux

$ stat /proc/self/fd/0
  File: /proc/self/fd/0 -> /dev/pts/1
  Size: 64        	Blocks: 0          IO Block: 1024   symbolic link
Device: 5h/5d	Inode: 5267070     Links: 1
Access: (0700/lrwx------)  Uid: ( 1000/overcrook)   Gid: ( 1001/overcrook)
Access: 2020-05-27 01:01:58.404658265 +0300
Modify: 2020-05-27 01:01:58.404658265 +0300
Change: 2020-05-27 01:01:58.404658265 +0300
 Birth: -

$ readlink /proc/self/fd/0
/dev/pts/1

$ readlink /proc/self/fd/0 | wc -c
11

$ lua -e "readlink = require('posix.unistd').readlink; print(readlink('/proc/self/fd/0'))"
nil	/proc/self/fd/0: readlink wrote only 10 of 64 bytes
```

The cause of this behaviour is the retvalue check at `ext/posix/unistd.c +1004`:
```
	n = readlink(path, b, bufsiz);
	err = errno; /* save readlink error code, if any */
	if (n > 0)
		lua_pushlstring(L, b, n);
	lalloc(ud, b, bufsiz, 0);

	/* report new errors from this function */
	if (n < 0)
	{
		errno = err; /* restore readlink error code */
		return pusherror(L, "readlink");
	}
	else if (n < s.st_size)    ///< here
	{
		lua_pushnil(L);
		lua_pushfstring(L, "%s: readlink wrote only %d of %d bytes", path, n, s.st_size);
		return 2;
	}
```

I'm wondering if this extra check is really needed. I'm not sure if readlink() can actually fail here, because the length of a result is already known and a sufficient buffer is provided.

**Comment by gvvaughan** [comment]
The kernel may legitimately write less than the full buffer, so I think the check is useful.

I'd accept a patch that also accepts n==64 on linux for special files though.

**Comment by kedorlaomer** [comment]
The [manpage](https://manpages.debian.org/buster/manpages-dev/readlink.2.en.html) for readlink(2) and the [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/functions/readlink.html) don't mention the possibility that only a partial path may be written. Instead, they mention the _opposite_ possibility: If the path is too long, maybe only the first few bytes are written. The example given in the manpage shows how to detect it. Our code seems to be safe unless someone changes the symlink between `lstat` and `readlink`. I attached a [diff](https://github.com/luaposix/luaposix/files/5995538/readlink-fails-on-short-filename.txt) showing how I resolved this in my private copy of luaposix (I came across this behaviour today). Feel free to merge it if you think it's helpful.

**Comment by fstirlitz** [comment]
Expecting that the pathname length returned by `stat` will be accurate by the time you perform `readlink` is a built-in TOCTOU race condition anyway. You should drop the `stat` call and just call `readlink` in a loop with exponentially increasing buffer size until it succeeds.
