### ISSUE TITLE
question, documentation: posix.unistd.execp

### ISSUE THREAD

**Issue by zhiburt** [luaposix/luaposix#329]
I've just started using lua. And coincidentally I've noticed an inconsistency between the function `posix.unistd.execp` and the documentation. As I understand it has a third return parameter but there's no information about it in the documentation.

https://luaposix.github.io/luaposix/modules/posix.unistd.html#execp

```
execp (path, argt)
    ...
    Returns:
        nil
        string error message
    ... 
``` 

Example:

```lua
local e, err, code = unistd.execp("NOT_EXISTED_PROGRAM")
print(e, err, code, posix.errno(code))
      
--nil     NOT_EXISTED_PROGRAM: No such file or directory  2       No such file or directory       2

```

BTW: It has a outstanding documentation.

**Comment by gvvaughan** [comment]
Thanks for the prompt to ensure we have better consistency in the docs.  This will be in the next release.
