### ISSUE TITLE
Lua 5.4 support

### ISSUE THREAD

**Issue by junghans** [luaposix/luaposix#330]
Can you add lua-5.4 support?

Fedora has a patch for it: https://src.fedoraproject.org/rpms/lua-posix/blob/master/f/lua-posix-helpers-5.4.patch

**Comment by gvvaughan** [comment]
thanks for the reminder, and yes of course! any day now...

**Comment by gvvaughan** [comment]
Thanks for the hints @opoplawski, although I solved the `require` issue differently, and also changed the way bitwise operations are implemented so that this release works correctly for luarocks users too.

Resolved with https://github.com/luaposix/luaposix/releases/tag/v35.0

**Comment by opoplawski** [comment]
Thanks, looks good.
