### ISSUE TITLE
Incorrect fork error-handling

### ISSUE THREAD

**Issue by AiyionPrime** [luaposix/luaposix#340]
The docs make clear, fork() returns
> [...]
>
>    nil
>    string error message
>    int errnum

on error.

The example "fork2.lua" checks for a pid of `-1`.

https://github.com/luaposix/luaposix/blob/6ad51f74f631f27bee28b7a95988db75334fc9f7/doc/examples/fork2.lua#L10

Just found a downstream usage of that `-1`-check.
Possible, this is just me notyet getting a lua aspect regarding `nil`, but I think this is wrong and needs fixing.

**Comment by ardje** [comment]
fork:
https://github.com/luaposix/luaposix/blob/master/ext/posix/unistd.c#L410-L415
pushresult+pusherror:
https://github.com/luaposix/luaposix/blob/master/ext/include/_helpers.c#L322-L346

So yeah, childpid == -1 will not happen, so the example in fork2.lua is bad.

**Comment by gvvaughan** [comment]
Nice catch! Thanks for the report.  I decided to also capture and display the returned error from the example code, but thanks for providing a patch.
