### ISSUE TITLE
Using unix sockets in a non-blocking manner / timeouts

### ISSUE THREAD

**Issue by Nooo37** [luaposix/luaposix#344]
Is there a way to use the unix sockets (`posix.sys.socket`) that doesn't make them block the main thread until they receive data? Other libraries usually have the option to add a timeout or to check if there is data that can be read so maybe I just missed it in the docs. 

Good job and thanks for the library though :+1:

**Comment by gvvaughan** [comment]
I'm not an expert on the POSIX socket APIs, but luaposix is no more than a minimal wrapper of the C calls. Googling for how to set timeouts with POSIX sockets reveals:

```c
struct timeval tv;
tv.tv_sec = timeout_in_seconds;
tv.tv_usec = 0;
setsockopt(sockfd, SOL_SOCKET, SO_RCVTIMEO, (const char*)&tv, sizeof tv);
```
Translating that to Lua using luaposix APIs is pretty straight forward.

HTH,
Gary

**Comment by Nooo37** [comment]
Thanks for the quick answer! I will keep in mind to look for the C equivalents when using posixlua. Translating it was indeed very straight forward. For others interested:
```lua
local socket = require("posix.sys.socket")
-- ...
local timeval = 0 -- timeout in seconds
socket.setsockopt(fd, socket.SOL_SOCKET, socket.SO_RCVTIMEO, timeval, 1)
```
