### ISSUE TITLE
posix.sys.socket - recv() crashes with socket and timeout in v36.1 (v36.0)

### ISSUE THREAD

**Issue by matthias-hmb** [luaposix/luaposix#354]
Example code - tested with lua5.4:
```
psocket = require("posix.sys.socket")
socket = psocket.socket(psocket.AF_UNIX, psocket.SOCK_STREAM, 0)
os.remove("/tmp/psock")
psocket.bind(socket, {family = psocket.AF_UNIX, path = "/tmp/psock"})
psocket.listen(socket, 512)
con = psocket.accept(socket)
psocket.setsockopt(con, psocket.SOL_SOCKET, psocket.SO_RCVTIMEO, 0, 100)
print(psocket.recv(con, 65536))
```

-> run code and connect (e.g. socat - unix-connect:/tmp/psock), timeout will be fast

Result in luaposix 35.1 (as expected):
nil     Resource temporarily unavailable        11

Result in luaposix 36.X:
/usr/bin/lua5.4: memory allocation error: block too big
stack traceback:
    [C]: in function 'posix.sys.socket.recv'
    test.lua:8: in main chunk
    [C]: in ?
    
As far as I could see, it seems to happen on other errors too (trying to recv on closed socket)

Just tested. Same result with tcp socket, not only UNIX socket.

**Comment by jimdigriz** [comment]
There seems to be a similar problem if you try to use `O_NONBLOCK` too, as when [`recv()` produces `-EAGAIN` it returns NULL back to Lua](https://github.com/luaposix/luaposix/blob/master/ext/posix/sys/socket.c#L551-L556) which I think is leading to the `SIsegfaultGSEGV`:
```
socket(AF_UNIX, SOCK_STREAM, 0)         = 3
connect(3, {sa_family=AF_UNIX, sun_path="/var/agentx/master"}, 20) = 0
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
recvfrom(3, 0xaaab19cd5070, 20, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <--- sets us up for failure when there is nothing yet to read on the socket

fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x1), ...}) = 0
write(1, "\220Z\317\31\253\252\n", 7
)   = 7
sendto(3, "\1\1\20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\20\0\0\0\0\0\0\0\0\0\0\0\3"..., 36, 0, NULL, 0) = 36
recvfrom(3, "\1\22\20\0\0\0\0^\0\0\0\0\0\0\0\0\0\0\0 ", 20, 0, NULL, NULL) = 20
recvfrom(3, "\0a\313r\0\0\0\0\0\4\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\3EBM\0", 32, 0, NULL, NULL) = 32
write(1, "32\t32\n", 632        32
)                 = 6
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[INT], sa_flags=SA_RESTART}, {sa_handler=0xaaaae8366300, sa_mask=[INT], sa_flags=SA_RESTART}, 8) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x6f6e090a27617574} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

The code I am using is mostly:
```
local fd = assert(socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0))
local ok, err, e = socket.connect(self.fd, { family=socket.AF_UNIX, path=t.path })
if not ok then
    error(err)
end

local fdflags = fcntl.fcntl(self.fd, fcntl.F_GETFL)
assert(fcntl.fcntl(self.fd, fcntl.F_SETFL, bit32.bor(fdflags, fcntl.O_NONBLOCK)))

socket.recv(self.fd, 20) <--- sets us up for failure when there is nothing yet to read on the socket (also returns a string of 33 bytes though I asked for 20!)

[snipped do some more send/recv]
```

**Comment by silaswaxter** [comment]
@jimdigriz any luck? I've encountered a similar problem I think.  `strace` is also reporting a sigint when I try to receive when there is no data to read from the unix domain socket which I've configured to be nonblocking (via fcntl). 

I don't understand what is calling the SIGINT. When it occurs, lua exits with an error, `memory allocation error: block too big`, and a stack trace.

**Comment by jimdigriz** [comment]
> @jimdigriz any luck? I've encountered a similar problem I think. `strace` is also reporting a sigint when I try to receive when there is no data to read from the unix domain socket which I've configured to be nonblocking (via fcntl).

Without seeing your `strace` output, I would be surprised if you were seeing `SIGINT`. In an `strace` signals look like three hyphens followed by the signal name:
```
--- SIGPOOP ....
```

> I don't understand what is calling the SIGINT.

Maybe you are misreading the `rt_sigaction()`, which *configures* what to do when receiving a signal, with the actual signal shown in your ouput?

> When it occurs, lua exits with an error, `memory allocation error: block too big`, and a stack trace.

The memory/stack/everything has been obliterated, the behaviour of the code after the `recvfrom(...) = -1 EAGAIN` is undefined/random/destined-to-explode.

I suspect for you, the memory allocation problem is the same problem I mention at the end (I ask for 20 bytes but get 33) for you the Lua C-binding probably thinks (as half its memory has been carpet bombed) it now thinks it has read and needs to pass back to your Lua code 100GB+ of string or something.

**Comment by matthias-hmb** [comment]
There was one change in the source of posix.c between 35.1 and 36.x that is:
<pre>
- size_t count = checkint(L, 2), ret;
+ size_t count = (size_t)checkinteger(L, 2), ret;
</pre>

Changing from int to a size_t type is fine, but in that case it changed the return value of the recv function too, which needs to be ssize_t.
If not, it is an unsigned value, which will get an overflow and -1 will end up in a very big value:
-> no error handling, but trying to push a really big (NULL) string to lua...

(PS: the same happened in unistd.c Pread )

**Comment by silaswaxter** [comment]
> I suspect for you, the memory allocation problem is the same problem I mention at the end (I ask for 20 bytes but get 33) for you the Lua C-binding probably thinks (as half its memory has been carpet bombed) it now thinks it has read and needs to pass back to your Lua code 100GB+ of string or something.
@jimdigriz Thank you for explaining. I was confused, but ur explanation makes sense.

@gvvaughan I confirm the patch fixed the issue for me. Thank you! I took another look at the source with a better understanding. Shouldn't the type of `r` within `recvfrom` also be changed to `ssize_t`. I don't think the current type `int` will cause any bugs, but ideally the types would be consistent?

**Comment by gvvaughan** [comment]
Nice catch!  Yeah, `recv` and `recvfrom` should have almost identical implementations.  I've fixed that on master for the next reease.  Thanks.
