### ISSUE TITLE
Missing rockspec file in v36.1

### ISSUE THREAD

**Issue by p-linnane** [luaposix/luaposix#358]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging the new version of lmod we ran into some failures with luaposix. It appears there is no rockspec file in the tarball like there previously was. Wanted to get some clarification here. Thank you!

Relates to https://github.com/Homebrew/homebrew-core/pull/125872

**Comment by gvvaughan** [comment]
Hi Patrick,

I'm assuming you're referring to github release tarball contents?  It appears I left a bad tag for v36.1, but I've force pushed it to the right hashref and github has regenerated the release tarball accordingly.  Sorry about that, and thanks for the report!

Cheers!

**Comment by p-linnane** [comment]
Just wanted to confirm that that did fix the issue we were seeing. Thanks for your quick attention to this!

**Comment by nekopsykose** [comment]
please don't retag the same tag, it breaks the cached tag for anyone that already had it. just tag e.g. 36.1.1 instead.

**Comment by gvvaughan** [comment]
On April 9, 2023 10:22:24 PM MST, alice ***@***.***> wrote:
>please don't retag the same tag, it breaks the cached tag for anyone that already had it. just tag e.g. 36.1.1 instead.
>

H Alice,

Thanks for the feedback.

Your advice is good for branches, but you can (arguably: should) update the hashrefs referenced by the tags in your working copy with `git fetch origin --tags --force`.

However, I would normally refrain from moving tags around, except that in this case the tag that was used by github for the release tarball fetched by the luarocks rockspec was pointed at a detached HEAD. It was much easier, to move that tag to the correct release branch than pull all the borked files from luarocks and github (while still leaving that release tag on the wrong branch for anyone looking in the future), and then make a whole new release to pull in the missing file... This also helps distros that package that release without forcing them to bump package versions and rerelease.

Cheers,
Gary

**Comment by nekopsykose** [comment]
> but you can (arguably: should)  
you should never do this: https://git-scm.com/docs/git-tag#_on_re_tagging  

it is also not something one can do (or even sees at all) when using the autogenerated tarball, e.g. `https://github.com/luaposix/luaposix/archive/refs/tags/v36.1.tar.gz`, which simply then changes and the checksums of it change. simply tagging v36.1.1 avoids all these issues.
