### ISSUE TITLE
String overflow for unistd.read().

### ISSUE THREAD

**Issue by ImagicTheCat** [luaposix/luaposix#361]
Hi,

it seems there is an integer "overflow" on `read()` error, `ret` is `size_t`.
https://github.com/luaposix/luaposix/blob/v36.1/ext/posix/unistd.c#L945

Which, in my case, causes a `string length overflow` (with LuaJIT, it is around 2GB).

**Comment by gvvaughan** [comment]
You don't say what platform or OS you are on.  How many bits are in your size_t? What type did you use for number in your LuaJIT build?

Do you have a minimal program to reproduce the error?  Does it only occur on LuaJIT?

Are you interested in working on a patch?

**Comment by ImagicTheCat** [comment]
Can confirm that by fixing the overflow I could see the actual error underneath: a bad file descriptor error from `read()` (which is its own mystery, but orthogonal to this issue).

**Comment by gvvaughan** [comment]
Awesome catch, thanks for reporting and especially for also providing a fix. I expect to be able to integrate your fix the weekend after next (I'm on my phone without a computer until then). If you'd like it to be upstreamed sooner, a PR with your fix, along with a test case that passes GitHub CI to exercise it so we don't accidentally reintroduce the problem in future would be great! I can hit merge from my phone in that case 👍

**Comment by gvvaughan** [comment]
The bad descriptor is a symptom of this issue: https://github.com/luaposix/luaposix/issues/217

 Different  implementations of Lua wrap file objects differently, and until we figure out how to portably wrap a libc descriptor up in a Lua file object, you can't use luaposix files in Lua io calls, and vice versa 😖

**Comment by ImagicTheCat** [comment]
>  I expect to be able to integrate your fix the weekend after next [...]

Thanks. Even if it's just changing a variable type, I don't want to mess with GitHub and I'm not in a hurry.

> The bad descriptor is a symptom of this issue: https://github.com/luaposix/luaposix/issues/217

I encountered that issue, but I'm only using `stdio.fileno`, which should be fine.

(In my case, the error was on reading a pipe.)
