### ISSUE TITLE
studio code does not seems to like the require 

### ISSUE THREAD

**Issue by konstantinosDMS** [luaposix/luaposix#368]
My > print(package.path)
/usr/local/bin/lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;/usr/local/lib/lua/5.4/?.lua;/usr/local/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua
My > print(package.cpath)
/usr/local/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/posix/sys/

My echo $LUA_CPATH
/usr/local/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/posix/sys/
My echo $LUA_PATH
/usr/local/bin/lua;;

my v.code:
module 'posix.signal' not found:
        no field package.preload['posix.signal']
        no file '/home/konstantinos/Desktop/server/lua-apps/posix/signal.lua'
        no file '/home/konstantinos/Desktop/server/lua-apps/posix/signal.lua'
        no file '/home/konstantinos/Desktop/server/lua-apps/posix/signal.so'
        no file '/home/konstantinos/Desktop/server/lua-apps/posix/signal.so'
        no file '/home/konstantinos/Desktop/server/lua-apps/posix.so'
        no file '/home/konstantinos/Desktop/server/lua-apps/posix.so'
on local posix = require('posix.signal'), seraches on the path i  have my deployment folder.Any suggestion?

**Comment by gvvaughan** [comment]
I'm a vi and emacs user. You could ask on the Lua mailing list for help from other visual studio users, or maybe there is a visual studio forum that had Lua users on it?

**Comment by gvvaughan** [comment]
...of course I'm assuming that you have installed both luaposix dsos somewhere on your LUA_CPATH, and the all the luaposix .lua modules on somewhere on your LUA_PATH. My best guess is that visual studio has its own settings for those paths instead of respecting your environment values?
