### ISSUE TITLE
'posix' won't load: module bit32 not found

### ISSUE THREAD

**Issue by Botster** [luaposix/luaposix#376]
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> local posix = require 'posix'
/usr/share/lua/5.1/posix/_base.lua:29: module 'bit32' not found:
        no field package.preload['bit32']
        no file './bit32.lua'
        no file '/usr/local/share/lua/5.1/bit32.lua'
        no file '/usr/local/share/lua/5.1/bit32/init.lua'
        no file '/usr/local/lib64/lua/5.1/bit32.lua'
        no file '/usr/local/lib64/lua/5.1/bit32/init.lua'
        no file '/usr/share/lua/5.1/bit32.lua'
        no file '/usr/share/lua/5.1/bit32/init.lua'
        no file './bit32.so'
        no file '/usr/local/lib64/lua/5.1/bit32.so'
        no file '/usr/lib64/lua/5.1/bit32.so'
        no file '/usr/local/lib64/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/share/lua/5.1/posix/_base.lua:29: in main chunk
        [C]: in function 'require'
        /usr/share/lua/5.1/posix/init.lua:30: in main chunk
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: ?
> 

Machine:
`grep PRETTY_NAME /etc/os-release`
PRETTY_NAME="openSUSE Leap 15.6"

`uname -a`
Linux desktop 6.4.0-150600.23.7-default #1 SMP PREEMPT_DYNAMIC Fri Jun 14 14:33:11 UTC 2024 (33f31da) x86_64 x86_64 x86_64 GNU/Linux

openSUSE package info:
`zypper info lua51-luaposix`
Information for package lua51-luaposix:
---------------------------------------
Repository     : Update repository with updates from SUSE Linux Enterprise 15
Name           : lua51-luaposix
Version        : 34.1.1-150200.3.5.1
Arch           : x86_64
Vendor         : SUSE LLC <https://www.suse.com/>
Installed Size : 792.5 KiB
Installed      : Yes
Status         : up-to-date
Source package : lua51-luaposix-34.1.1-150200.3.5.1.src
Upstream URL   : https://github.com/luaposix/luaposix
Summary        : POSIX library for Lua

I found issue #43 [https://github.com/luaposix/luaposix/issues/43] and installed 'lua51-BitOp'. But that provides 'bit.so'' not 'bit32.so':
`rpm -ql lua51-BitOp`
/usr/lib64/lua/5.1
/usr/lib64/lua/5.1/bit.so
/usr/share/doc/packages/lua51-BitOp
/usr/share/doc/packages/lua51-BitOp/README

And, it appears that Bit32 for lua51 is not available from luarocks:
`luarocks search bit32`

Search results:
===============

Rockspecs and source rocks:
---------------------------

bit32
   5.3.5.1-1 (rockspec) - https://luarocks.org
   5.3.5.1-1 (src) - https://luarocks.org
   5.3.5-1 (rockspec) - https://luarocks.org
   5.3.5-1 (src) - https://luarocks.org
   5.3.0-1 (rockspec) - https://luarocks.org
   5.3.0-1 (src) - https://luarocks.org
   5.2.2-1 (rockspec) - https://luarocks.org
   5.2.2-1 (src) - https://luarocks.org
   5.2.0alpha.1-1 (rockspec) - https://luarocks.org
   5.2.0alpha.1-1 (src) - https://luarocks.org

This issue surfaced, quite confusingly, after the 'posix' module had previously (apparently) successfully loaded. I made no changes to the system in between. The only thing I did was try to load 'posix' from the Lua shell. It failed, and then the script I was trying to execute also failed.

I'm baffled.

**Comment by gvvaughan** [comment]
works for me: https://github.com/luaposix/luaposix/actions/runs/10049748186/job/27776375541
