### ISSUE TITLE
luaposix build failed: required symbol 'crypt' not found in any of libc, libcrypt

### ISSUE THREAD

**Issue by cattokomo** [luaposix/luaposix#379]
OS: NixOS 24.05
Lua: 5.4.6
Luarocks: 3.11.0

```
Installing https://luarocks.org/luaposix-36.2.1-1.src.rock

luaposix 36.2.1-1 depends on lua >= 5.1, < 5.5 (5.4-1 provided by VM: success)
/nix/store/60djkmpzmyv5r2w77p855b58mpgxc1cm-lua-5.4.6/bin/lua build-aux/luke package="luaposix" version="36.2.1" PREFIX="/home/komo/Projects/null/lua_modules/lib/luarocks/rocks-5.4/luaposix/36.2.1-1" LUA="/nix/store/60djkmpzmyv5r2w77p855b58mpgxc1cm-lua-5.4.6/bin/lua" LUA_INCDIR="/nix/store/60djkmpzmyv5r2w77p855b58mpgxc1cm-lua-5.4.6/include" CC="clang" LD="clang" CFLAGS="-O2 -fPIC" LIBFLAG="-shared" LIB_EXTENSION="so" OBJ_EXTENSION="o" INST_LIBDIR="/home/komo/Projects/null/lua_modules/lib/luarocks/rocks-5.4/luaposix/36.2.1-1/lib" INST_LUADIR="/home/komo/Projects/null/lua_modules/lib/luarocks/rocks-5.4/luaposix/36.2.1-1/lua"
luke: fatal: required symbol 'crypt' not found in any of libc, libcrypt

Error: Failed installing dependency: https://luarocks.org/luaposix-36.2.1-1.src.rock - Build error: Failed building.
```

Might related to #343

**Comment by cattokomo** [comment]
The issue resolved by installing `libxcrypt`, but this still is an unintended behavior.

**Comment by gvvaughan** [comment]
Thanks for the report and the solution!

It's unfortunate that nixOS doesn't provide the crypt APIs in a standard library.  I've never heard of `libxcrypt` on any other UNIX, and I'm not sure even `libcrypt` is used on any modern UNIX.  I guess that means that it doesn't follow POSIX and provide the prototypes for `crypt` and `encrypt` in `unistd.h`?  Or is `unistd.h` standard, but provides proper function prototypes, but calls to `crypt` make the compiler fall over?

Can you show me the `SYNOPSIS` section of the nixOS `crypt` manpage please?

**Comment by cattokomo** [comment]
```
SYNOPSIS
       #include <crypt.h>

       char *
       crypt(const char *phrase, const char *setting);

       char *
       crypt_r(const char *phrase, const char *setting, struct crypt_data *data);

       char *
       crypt_rn(const char *phrase, const char *setting, struct crypt_data *data, int size);

       char *
       crypt_ra(const char *phrase, const char *setting, void **data, int *size);
```
<br>

Also about missing `libcrypt`, it was explained in [NixOS 22.11 release notes](https://nixos.org/manual/nixos/stable/release-notes.html#sec-release-22.11-highlights).
> Software that uses the **crypt** password hashing API is now using the implementation provided by [libxcrypt](https://github.com/besser82/libxcrypt) instead of glibc’s, which enables support for more secure algorithms.

**Comment by gvvaughan** [comment]
That's all very non-standard, so I'm not surprised that luaposix is unable to find all the right pieces.  I recommend that you rename libxcrypt.so to libcrypt.so, so that other package builds don't all need to be taught an extra location for the library that provides the crypt() APIs.

In the mean time, I'd accept a patch to `lukefile` to make it fallback to libxcrypt if both libc and libcrypt fail to compile a test program that calls crypt.  The syntax is pretty self explanatory, but boils down to changing `library='crypt'` to `libraries={'crypt', 'xcrypt'}` (from memory, so please test it).

**Comment by cattokomo** [comment]
Afaik, libxcrypt is compiled as `libcrypt.so`. So it's not necesarry to patch `lukefile`. But adding a notice about missing `libcrypt` would be useful. E.g checking any news about your OS deprecation notice of the libc's crypt in favor of libxcrypt.

**Comment by cattokomo** [comment]
> So, seems like everything is working as expected then? The error message from `luke` already described the problem:
> 
> ```
> luke: fatal: required symbol 'crypt' not found in any of libc, libcrypt
> ```

Yes, pretty much.
