### ISSUE TITLE
posix.pipeline doesn't restore stdout properly

### ISSUE THREAD

**Issue by rrthomas** [luaposix/luaposix#81]
See https://savannah.gnu.org/patch/index.php?8007 for a demonstration of the problem (in an editor, using posix.pipeline messes up the terminal).

The advice given here: http://stackoverflow.com/questions/11042218/c-restore-stdout-to-terminal is exactly what posix.pipeline does (independently!), so I'm not sure what the problem is.

**Comment by rrthomas** [comment]
I now have a use case for this: cw has an (obvious-in-hindsight) bug rrthomas/cw#4 in that it doesn't return exit codes of commands that it colors, because `pipeline_iterator` doesn't give access to those exit codes. The `sh` API for Python does, by making each command an object with an iterator property and an exit code property.

**Comment by rrthomas** [comment]
Looking at `sh`, it is (now?) a large module, some 2kLOC long. I'm not keen to reimplement it in one go, nor am I over-fond of its API (other than the command→function transformer).

**Comment by rrthomas** [comment]
I just spotted a possible clue as to why stdout-restoring isn't working. One of the comments in the stackoverflow page linked above says: "You do need to worry about flushing standard I/O streams (fflush(stdout)) at appropriate times as you mess around with this. That means 'before you switch stdout over'."

**Comment by gvvaughan** [comment]
Wow, you're right the implementation of Python's `sh` is ugly :-(  Still, if we can make pipelines work properly, who cares!! :-p LOL

**Comment by gvvaughan** [comment]
This is still on my radar, soon after I climb back up the dependency stack to Zile (which, realistically speaking is likely quite some way in the future by now)... but it would be awesome if you can try injecting some stream flushes judiciously and get it working properly in the mean time...

**Comment by rrthomas** [comment]
​I have been wrestling with this, but in a different direction: the current
pipeline function requires two forks per task, one for the subprocess with
the pipe, and another to spawn the task. It seemed to me that a
one-fork-per-task model which worked like popen would be better. I did try
this when I wrote pipeline, but got stuck and gave up.

I've now got it working.

Of course for safe use, as with popen, you need to decide whether you want
to read or write the pipeline, but not both, to avoid deadlocking. Once
I've got the code shaken down, I can work out whether it makes sense to
have a bidirectional version internally or not; currently I don't, as you'd
need an extra pipe. Of course, if you want to read and write safely, you
can just add another process to the end of the ​chain, like pipeline_slurp.

I'm still playing with the structure of the code; once I converge, I'll
share.

**Comment by gvvaughan** [comment]
Awesome!

**Comment by gvvaughan** [comment]
34c8aeb replaces the troublesome `pipeline` with `popen_pipeline` by cherry-picking from #212
